/* Agence Ruelas — catalogue public (éditable). Grille tours : provisoire jusqu'aux données officielles. */
function wikiPhoto(file) {
  return 'https://commons.wikimedia.org/wiki/Special:FilePath/' + encodeURIComponent(file) + '?width=1600';
}

window.RUELAS = {
  CONFIG: {
    brand: 'Agence Ruelas',
    city: 'Lisboa',
    phone: '+351 21 000 00 00',
    whatsapp: '351210000000',
    email: 'reservas@agenceruelas.pt',
    hours: '24/7',
    apiUrl: '',
    storageKey: 'ruelas_site_bookings_v1',
    usersKey: 'ruelas_site_users_v1',
    sessionKey: 'ruelas_site_session_v1',
    pricesProvisional: true,
    defaultLang: 'pt'
  },

  AIRPORTS: [
    { id: 'lis-t1', name: 'Aeroporto de Lisboa (LIS) — Terminal 1', type: 'airport' },
    { id: 'lis-t2', name: 'Aeroporto de Lisboa (LIS) — Terminal 2', type: 'airport' }
  ],

  STATIONS_TRAIN: [
    { id: 'tr-oriente', name: 'Gare do Oriente', type: 'train', line: 'CP / Comboios de Portugal' },
    { id: 'tr-santa', name: 'Santa Apolónia', type: 'train', line: 'CP' },
    { id: 'tr-sete', name: 'Sete Rios', type: 'train', line: 'CP / Terminal rodoviário' },
    { id: 'tr-entrecampos', name: 'Entrecampos', type: 'train', line: 'CP' },
    { id: 'tr-cais', name: 'Cais do Sodré', type: 'train', line: 'Linha de Cascais' },
    { id: 'tr-rossio', name: 'Rossio', type: 'train', line: 'Linha de Sintra' },
    { id: 'tr-roma', name: 'Roma-Areeiro', type: 'train', line: 'CP' },
    { id: 'tr-campolide', name: 'Campolide', type: 'train', line: 'CP' },
    { id: 'tr-alcantara-t', name: 'Alcântara-Terra', type: 'train', line: 'CP' },
    { id: 'tr-alcantara-m', name: 'Alcântara-Mar', type: 'train', line: 'Linha de Cascais' },
    { id: 'tr-belem', name: 'Belém', type: 'train', line: 'Linha de Cascais' },
    { id: 'tr-oeiras', name: 'Oeiras', type: 'train', line: 'Linha de Cascais' },
    { id: 'tr-estoril', name: 'Estoril', type: 'train', line: 'Linha de Cascais' },
    { id: 'tr-cascais', name: 'Cascais', type: 'train', line: 'Linha de Cascais' },
    { id: 'tr-sintra', name: 'Sintra', type: 'train', line: 'Linha de Sintra' }
  ],

  STATIONS_METRO: [
    { id: 'mt-aeroporto', name: 'Metro Aeroporto', type: 'metro', line: 'Vermelha' },
    { id: 'mt-oriente', name: 'Metro Oriente', type: 'metro', line: 'Vermelha' },
    { id: 'mt-saldanha', name: 'Metro Saldanha', type: 'metro', line: 'Vermelha / Amarela' },
    { id: 'mt-alameda', name: 'Metro Alameda', type: 'metro', line: 'Vermelha / Verde' },
    { id: 'mt-marques', name: 'Metro Marquês de Pombal', type: 'metro', line: 'Azul / Amarela' },
    { id: 'mt-baixa', name: 'Metro Baixa-Chiado', type: 'metro', line: 'Azul / Verde' },
    { id: 'mt-terreiro', name: 'Metro Terreiro do Paço', type: 'metro', line: 'Azul' },
    { id: 'mt-cais', name: 'Metro Cais do Sodré', type: 'metro', line: 'Verde' },
    { id: 'mt-restauradores', name: 'Metro Restauradores', type: 'metro', line: 'Azul' },
    { id: 'mt-avenida', name: 'Metro Avenida', type: 'metro', line: 'Azul' },
    { id: 'mt-sao-seb', name: 'Metro São Sebastião', type: 'metro', line: 'Azul / Vermelha' },
    { id: 'mt-campo-grande', name: 'Metro Campo Grande', type: 'metro', line: 'Amarela / Verde' },
    { id: 'mt-entrecampos', name: 'Metro Entrecampos', type: 'metro', line: 'Amarela' },
    { id: 'mt-rato', name: 'Metro Rato', type: 'metro', line: 'Amarela' },
    { id: 'mt-picoas', name: 'Metro Picoas', type: 'metro', line: 'Amarela' },
    { id: 'mt-parque', name: 'Metro Parque', type: 'metro', line: 'Azul' },
    { id: 'mt-santa', name: 'Metro Santa Apolónia', type: 'metro', line: 'Azul' },
    { id: 'mt-rossio', name: 'Metro Rossio', type: 'metro', line: 'Verde' },
    { id: 'mt-martim', name: 'Metro Martim Moniz', type: 'metro', line: 'Verde' },
    { id: 'mt-intendente', name: 'Metro Intendente', type: 'metro', line: 'Verde' },
    { id: 'mt-colegio', name: 'Metro Colégio Militar / Luz', type: 'metro', line: 'Azul' },
    { id: 'mt-espanha', name: 'Metro Praça de Espanha', type: 'metro', line: 'Azul' },
    { id: 'mt-zoo', name: 'Metro Jardim Zoológico', type: 'metro', line: 'Azul' },
    { id: 'mt-campo-pequeno', name: 'Metro Campo Pequeno', type: 'metro', line: 'Amarela' }
  ],

  HOTELS: [
    /* remplacé par hotels.js — liste exhaustive Lisboa */
    { id: 'h-tivoli-lib', name: 'Tivoli Avenida da Liberdade Lisboa', area: 'Avenida da Liberdade' },
    { id: 'h-tivoli-or', name: 'Tivoli Oriente Lisboa', area: 'Parque das Nações' },
    { id: 'h-corinthia', name: 'Corinthia Hotel Lisbon', area: 'Sete Rios' },
    { id: 'h-epic', name: 'EPIC SANA Marquês', area: 'Marquês de Pombal' },
    { id: 'h-sheraton', name: 'Sheraton Lisboa Hotel & Spa', area: 'Parque' },
    { id: 'h-pestana-pal', name: 'Pestana Palace Lisboa', area: 'Santo Amaro' },
    { id: 'h-pestana-cr7', name: 'Pestana CR7 Lisboa', area: 'Baixa' },
    { id: 'h-altis-grand', name: 'Altis Grand Hotel', area: 'Avenida da Liberdade' },
    { id: 'h-altis-belem', name: 'Altis Belém Hotel & Spa', area: 'Belém' },
    { id: 'h-memmo-alf', name: 'Memmo Alfama', area: 'Alfama' },
    { id: 'h-memmo-pr', name: 'Memmo Príncipe Real', area: 'Príncipe Real' },
    { id: 'h-bairro-alto', name: 'Bairro Alto Hotel', area: 'Chiado' },
    { id: 'h-one-palacio', name: 'The One Palácio da Anunciada', area: 'Avenida da Liberdade' },
    { id: 'h-ludovice', name: 'Palácio Ludovice Wine Experience Hotel', area: 'Chiado' },
    { id: 'h-avenida-palace', name: 'Hotel Avenida Palace', area: 'Restauradores' },
    { id: 'h-intercont', name: 'InterContinental Lisbon', area: 'Saldanha' },
    { id: 'h-sofitel', name: 'Sofitel Lisbon Liberdade', area: 'Avenida da Liberdade' },
    { id: 'h-olissippo-lapa', name: 'Olissippo Lapa Palace', area: 'Lapa' },
    { id: 'h-olissippo-castelo', name: 'Olissippo Castelo', area: 'Castelo' },
    { id: 'h-valverde', name: 'Valverde Hotel', area: 'Avenida da Liberdade' },
    { id: 'h-lumiares', name: 'The Lumiares Hotel & Spa', area: 'Bairro Alto' },
    { id: 'h-santiago', name: 'Santiago de Alfama — Boutique Hotel', area: 'Alfama' },
    { id: 'h-solar-castelo', name: 'Solar do Castelo', area: 'Castelo' },
    { id: 'h-myriad', name: 'Myriad by SANA', area: 'Parque das Nações' },
    { id: 'h-nh-lib', name: 'NH Collection Lisboa Liberdade', area: 'Avenida da Liberdade' },
    { id: 'h-radisson', name: 'Radisson Blu Lisbon', area: 'Parque das Nações' },
    { id: 'h-marriott', name: 'Lisbon Marriott Hotel', area: 'Entrecampos' },
    { id: 'h-renaissance', name: 'Renaissance Lisbon Hotel', area: 'Avenida da Liberdade' },
    { id: 'h-doubletree', name: 'DoubleTree by Hilton Lisbon Fontana Park', area: 'Saldanha' },
    { id: 'h-hilton-baixa', name: 'Hilton Garden Inn Lisbon Baixa', area: 'Baixa' },
    { id: 'h-dom-pedro', name: 'Dom Pedro Palace', area: 'Marquês de Pombal' },
    { id: 'h-inspira', name: 'Inspira Liberdade Boutique Hotel', area: 'Liberdade' },
    { id: 'h-lx-boutique', name: 'LX Boutique Hotel', area: 'Cais do Sodré' },
    { id: 'h-vincci-baixa', name: 'Vincci Baixa', area: 'Baixa' },
    { id: 'h-vincci-lib', name: 'Vincci Liberdade', area: 'Liberdade' },
    { id: 'h-eurostars-letras', name: 'Eurostars das Letras', area: 'Avenida da Liberdade' },
    { id: 'h-turim-terreiro', name: 'Turim Terreiro do Paço', area: 'Baixa' },
    { id: 'h-turim-lib', name: 'Turim Av. Liberdade', area: 'Liberdade' },
    { id: 'h-hf-fenix', name: 'HF Fénix Lisboa', area: 'Marquês de Pombal' },
    { id: 'h-jupiter', name: 'Jupiter Lisboa Hotel', area: 'Saldanha' },
    { id: 'h-florida', name: 'Hotel Florida', area: 'Marquês de Pombal' },
    { id: 'h-britania', name: 'Hotel Britania', area: 'Liberdade' },
    { id: 'h-mundial', name: 'Hotel Mundial', area: 'Rossio' },
    { id: 'h-portugal', name: 'Hotel Portugal', area: 'Baixa' },
    { id: 'h-pessoa', name: 'Lisboa Pessoa Hotel', area: 'Chiado' },
    { id: 'h-mystory-rossio', name: 'My Story Hotel Rossio', area: 'Rossio' },
    { id: 'h-tryp-aero', name: 'Tryp Lisboa Aeroporto', area: 'Aeroporto' },
    { id: 'h-ibis-aero', name: 'ibis Lisboa Aeroporto', area: 'Aeroporto' },
    { id: 'h-ibis-saldanha', name: 'ibis Lisboa Centro Saldanha', area: 'Saldanha' },
    { id: 'h-holiday-inn', name: 'Holiday Inn Lisbon — Continental', area: 'Entrecampos' },
    { id: 'h-sana-lisboa', name: 'SANA Lisboa Hotel', area: 'Saldanha' },
    { id: 'h-baia-cascais', name: 'Hotel Baía Cascais', area: 'Cascais' },
    { id: 'h-farol', name: 'Farol Hotel Cascais', area: 'Cascais' },
    { id: 'h-pestana-cidadela', name: 'Pestana Cidadela Cascais', area: 'Cascais' },
    { id: 'h-cascade', name: 'Cascade Wellness & Lifestyle Resort', area: 'Cascais' }
  ],

  VEHICLES: [
    { id: 'sedan', nameKey: 'vSedan', models: 'Škoda Superb / Peugeot 508', pax: 3, bags: 3, price: 35, badgeKey: 'vBadgeEco' },
    { id: 'vip', nameKey: 'vVip', models: 'Mercedes-Benz Classe E / S', pax: 3, bags: 3, price: 75, badgeKey: 'vBadgeVip' },
    { id: 'van', nameKey: 'vVan', models: 'Mercedes-Benz Classe V', pax: 7, bags: 7, price: 95, badgeKey: 'vBadgeFamily' },
    { id: 'sprinter', nameKey: 'vSprinter', models: 'Mercedes-Benz Sprinter', pax: 15, bags: 15, price: 160, badgeKey: 'vBadgeGroup' }
  ],

  OPTIONS: [
    { id: 'baby_seat', nameKey: 'optBaby', descKey: 'optBabyDesc', price: 10 },
    { id: 'meet_greet', nameKey: 'optMeet', descKey: 'optMeetDesc', price: 15 },
    { id: 'extra_stop', nameKey: 'optStop', descKey: 'optStopDesc', price: 20 },
    { id: 'refresh', nameKey: 'optRefresh', descKey: 'optRefreshDesc', price: 25 }
  ],

  TOURS: [
    {
      id: 'sintra-cascais',
      durationH: 8,
      image: wikiPhoto('Sintra Portugal Palácio da Pena-01.jpg'),
      title: { pt: 'Sintra, Palácio da Pena & Cascais', en: 'Sintra, Pena Palace & Cascais', fr: 'Sintra, Palais de Pena & Cascais', es: 'Sintra, Palacio de Pena y Cascais' },
      desc: {
        pt: 'Dia completo: Palácio da Pena, centro histórico de Sintra, Cabo da Roca e a vila marítima de Cascais.',
        en: 'Full day: Pena Palace, historic Sintra, Cabo da Roca and the seaside town of Cascais.',
        fr: 'Journée complète : Palais de Pena, Sintra historique, Cabo da Roca et Cascais.',
        es: 'Día completo: Palacio de Pena, Sintra histórica, Cabo da Roca y Cascais.'
      },
      includes: { pt: ['Motorista privado', 'Cabo da Roca', 'Tempo livre em Cascais'], en: ['Private driver', 'Cabo da Roca', 'Free time in Cascais'], fr: ['Chauffeur privé', 'Cabo da Roca', 'Temps libre à Cascais'], es: ['Chófer privado', 'Cabo da Roca', 'Tiempo libre en Cascais'] },
      private: [{ pax: '1–3', price: 280 }, { pax: '4–7', price: 340 }],
      sharedPerPerson: 75,
      sharedMin: 4,
      stops: [
        {
          id: 'pena',
          name: { pt: 'Palácio da Pena', en: 'Pena Palace', fr: 'Palais de Pena', es: 'Palacio de Pena' },
          photos: [
            { file: 'Sintra Portugal Palácio da Pena-01.jpg', cap: { pt: 'Fachada do Palácio Nacional da Pena', en: 'Pena National Palace façade', fr: 'Façade du Palais national de Pena', es: 'Fachada del Palacio Nacional de Pena' } },
            { file: 'View of Palácio Nacional da Pena-1453029.jpg', cap: { pt: 'Pena visto da serra de Sintra', en: 'Pena from the Sintra hills', fr: 'Pena vue depuis la sierra', es: 'Pena desde la sierra de Sintra' } },
            { file: 'Palácio Nacional da Pena - 22.jpg', cap: { pt: 'Torres e pátio interior', en: 'Towers and inner courtyard', fr: 'Tours et cour intérieure', es: 'Torres y patio interior' } }
          ]
        },
        {
          id: 'regaleira',
          name: { pt: 'Quinta da Regaleira', en: 'Quinta da Regaleira', fr: 'Quinta da Regaleira', es: 'Quinta da Regaleira' },
          photos: [
            { file: 'Initiation Well, Quinta da Regaleira.JPG', cap: { pt: 'Poço iniciático da Regaleira', en: 'Initiation well at Regaleira', fr: 'Puits initiatique de la Regaleira', es: 'Pozo iniciático de la Regaleira' } },
            { file: 'Quinta da Regaleira (36620779922).jpg', cap: { pt: 'Palácio e jardins da Regaleira', en: 'Regaleira palace and gardens', fr: 'Palais et jardins de la Regaleira', es: 'Palacio y jardines de la Regaleira' } }
          ]
        },
        {
          id: 'roca',
          name: { pt: 'Cabo da Roca', en: 'Cabo da Roca', fr: 'Cabo da Roca', es: 'Cabo da Roca' },
          photos: [
            { file: 'Farol Cabo da Roca.jpg', cap: { pt: 'Farol no ponto mais ocidental da Europa', en: 'Lighthouse at Europe’s westernmost point', fr: 'Phare au point le plus à l’ouest d’Europe', es: 'Faro en el punto más occidental de Europa' } },
            { file: 'Farol do Cabo da Roca, Cabo da Roca, the westernmost point of continental Europe (50657914401).jpg', cap: { pt: 'Falésias do Cabo da Roca', en: 'Cabo da Roca cliffs', fr: 'Falaises du Cabo da Roca', es: 'Acantilados de Cabo da Roca' } }
          ]
        },
        {
          id: 'sintra-town',
          name: { pt: 'Centro histórico de Sintra', en: 'Historic Sintra', fr: 'Sintra historique', es: 'Sintra histórica' },
          photos: [
            { file: 'Palácio Nacional de Sintra (36678680331).jpg', cap: { pt: 'Palácio Nacional de Sintra', en: 'Sintra National Palace', fr: 'Palais national de Sintra', es: 'Palacio Nacional de Sintra' } },
            { file: 'Castelo dos Mouros (Sintra) September 2013-2a.jpg', cap: { pt: 'Castelo dos Mouros', en: 'Moorish Castle', fr: 'Château des Maures', es: 'Castillo de los Moros' } }
          ]
        }
      ]
    },
    {
      id: 'cascais-estoril',
      durationH: 5,
      image: wikiPhoto('Cascais (15197815938).jpg'),
      title: { pt: 'Cascais, Estoril & Costa do Sol', en: 'Cascais, Estoril & Sunny Coast', fr: 'Cascais, Estoril & Costa do Sol', es: 'Cascais, Estoril y Costa del Sol' },
      desc: {
        pt: 'Meio-dia na costa: Boca do Inferno, marina de Cascais, casino Estoril e praias da linha.',
        en: 'Half day on the coast: Boca do Inferno, Cascais marina, Estoril and the beach line.',
        fr: 'Demi-journée sur la côte : Boca do Inferno, marina de Cascais, Estoril.',
        es: 'Media jornada en la costa: Boca do Inferno, marina de Cascais, Estoril.'
      },
      includes: { pt: ['Percurso costeiro', 'Paragens fotográficas', 'Regresso ao hotel'], en: ['Coastal route', 'Photo stops', 'Return to hotel'], fr: ['Parcours côtier', 'Arrêts photo', 'Retour à l’hôtel'], es: ['Ruta costera', 'Paradas foto', 'Regreso al hotel'] },
      private: [{ pax: '1–3', price: 180 }, { pax: '4–7', price: 220 }],
      sharedPerPerson: 55,
      sharedMin: 4,
      stops: [
        {
          id: 'cascais-marina',
          name: { pt: 'Marina de Cascais', en: 'Cascais Marina', fr: 'Marina de Cascais', es: 'Marina de Cascais' },
          photos: [
            { file: 'Cascais (15197815938).jpg', cap: { pt: 'Baía e marina de Cascais', en: 'Cascais bay and marina', fr: 'Baie et marina de Cascais', es: 'Bahía y marina de Cascais' } },
            { file: 'Cascais Portugal (21194623996).jpg', cap: { pt: 'Centro de Cascais', en: 'Cascais town centre', fr: 'Centre de Cascais', es: 'Centro de Cascais' } }
          ]
        },
        {
          id: 'boca',
          name: { pt: 'Boca do Inferno', en: 'Boca do Inferno', fr: 'Boca do Inferno', es: 'Boca do Inferno' },
          photos: [
            { file: 'Boca do Inferno.JPG', cap: { pt: 'Falésia da Boca do Inferno', en: 'Boca do Inferno cliff', fr: 'Falaise de la Boca do Inferno', es: 'Acantilado de Boca do Inferno' } },
            { file: 'Boca do Inferno, Cascais.JPG', cap: { pt: 'Rebentação na Boca do Inferno', en: 'Waves at Boca do Inferno', fr: 'Vagues à la Boca do Inferno', es: 'Olas en Boca do Inferno' } }
          ]
        },
        {
          id: 'estoril',
          name: { pt: 'Estoril & praias', en: 'Estoril & beaches', fr: 'Estoril et plages', es: 'Estoril y playas' },
          photos: [
            { file: 'Casino Estoril.JPG', cap: { pt: 'Casino do Estoril', en: 'Estoril Casino', fr: 'Casino d’Estoril', es: 'Casino de Estoril' } },
            { file: 'Praia do Tamariz, Estoril.JPG', cap: { pt: 'Praia do Tamariz, Estoril', en: 'Tamariz beach, Estoril', fr: 'Plage de Tamariz, Estoril', es: 'Playa de Tamariz, Estoril' } }
          ]
        }
      ]
    },
    {
      id: 'fatima-obidos',
      durationH: 9,
      image: wikiPhoto('Santuário de Fátima 2015.jpg'),
      title: { pt: 'Fátima & Óbidos', en: 'Fátima & Óbidos', fr: 'Fátima & Óbidos', es: 'Fátima y Óbidos' },
      desc: {
        pt: 'Santuário de Fátima e a vila medieval muralhada de Óbidos. Dia completo a partir de Lisboa.',
        en: 'Fátima Sanctuary and the walled medieval town of Óbidos. Full day from Lisbon.',
        fr: 'Sanctuaire de Fátima et village médiéval d’Óbidos. Journée complète depuis Lisbonne.',
        es: 'Santuario de Fátima y villa medieval de Óbidos. Día completo desde Lisboa.'
      },
      includes: { pt: ['Santuário de Fátima', 'Óbidos intramuros', 'Motorista dedicado'], en: ['Fátima Sanctuary', 'Óbidos old town', 'Dedicated driver'], fr: ['Sanctuaire de Fátima', 'Óbidos', 'Chauffeur dédié'], es: ['Santuario de Fátima', 'Óbidos', 'Chófer dedicado'] },
      private: [{ pax: '1–3', price: 320 }, { pax: '4–7', price: 390 }],
      sharedPerPerson: 85,
      sharedMin: 4,
      stops: [
        {
          id: 'fatima',
          name: { pt: 'Santuário de Fátima', en: 'Sanctuary of Fátima', fr: 'Sanctuaire de Fátima', es: 'Santuario de Fátima' },
          photos: [
            { file: 'Santuário de Fátima 2015.jpg', cap: { pt: 'Basílica de Nossa Senhora do Rosário', en: 'Basilica of Our Lady of the Rosary', fr: 'Basilique Notre-Dame du Rosaire', es: 'Basílica de Nuestra Señora del Rosario' } },
            { file: 'Basílica da Santíssima Trindade, Fátima.jpg', cap: { pt: 'Basílica da Santíssima Trindade', en: 'Basilica of the Holy Trinity', fr: 'Basilique de la Sainte Trinité', es: 'Basílica de la Santísima Trinidad' } },
            { file: 'Capelinha das Aparições.jpg', cap: { pt: 'Capelinha das Aparições', en: 'Chapel of the Apparitions', fr: 'Chapelle des Apparitions', es: 'Capilla de las Apariciones' } },
            { file: 'Santuário de Fátima (Portugal).jpg', cap: { pt: 'Esplanada do Santuário', en: 'Sanctuary esplanade', fr: 'Esplanade du sanctuaire', es: 'Explanada del santuario' } }
          ]
        },
        {
          id: 'obidos',
          name: { pt: 'Óbidos medieval', en: 'Medieval Óbidos', fr: 'Óbidos médiévale', es: 'Óbidos medieval' },
          photos: [
            { file: 'Óbidos July 2018-5.jpg', cap: { pt: 'Muralhas de Óbidos', en: 'Óbidos town walls', fr: 'Remparts d’Óbidos', es: 'Murallas de Óbidos' } },
            { file: 'Castelo de Óbidos (4460060054).jpg', cap: { pt: 'Castelo de Óbidos', en: 'Óbidos Castle', fr: 'Château d’Óbidos', es: 'Castillo de Óbidos' } },
            { file: 'Rua Direita, Óbidos.jpg', cap: { pt: 'Rua Direita intramuros', en: 'Rua Direita inside the walls', fr: 'Rua Direita intramuros', es: 'Rua Direita intramuros' } }
          ]
        }
      ]
    },
    {
      id: 'lisbon-belem',
      durationH: 4,
      image: wikiPhoto('Torre Belém April 2009-4a.jpg'),
      title: { pt: 'Lisboa histórica & Belém', en: 'Historic Lisbon & Belém', fr: 'Lisbonne historique & Belém', es: 'Lisboa histórica y Belém' },
      desc: {
        pt: 'Torre de Belém, Mosteiro dos Jerónimos, Padrão dos Descobrimentos, Alfama e miradouros.',
        en: 'Belém Tower, Jerónimos Monastery, Monument to the Discoveries, Alfama and viewpoints.',
        fr: 'Tour de Belém, monastère des Hiéronymites, Padrão, Alfama et miradouros.',
        es: 'Torre de Belém, Monasterio de los Jerónimos, Padrão, Alfama y miradores.'
      },
      includes: { pt: ['Belém', 'Alfama', 'Miradouros'], en: ['Belém', 'Alfama', 'Viewpoints'], fr: ['Belém', 'Alfama', 'Belvédères'], es: ['Belém', 'Alfama', 'Miradores'] },
      private: [{ pax: '1–3', price: 140 }, { pax: '4–7', price: 180 }],
      sharedPerPerson: 45,
      sharedMin: 4,
      stops: [
        {
          id: 'belem-tower',
          name: { pt: 'Torre de Belém', en: 'Belém Tower', fr: 'Tour de Belém', es: 'Torre de Belém' },
          photos: [
            { file: 'Torre Belém April 2009-4a.jpg', cap: { pt: 'Torre de Belém no Tejo', en: 'Belém Tower on the Tagus', fr: 'Tour de Belém sur le Tage', es: 'Torre de Belém en el Tajo' } },
            { file: 'Torre de Belém April 2009-1.jpg', cap: { pt: 'Torre de Belém, pormenor', en: 'Belém Tower, detail', fr: 'Tour de Belém, détail', es: 'Torre de Belém, detalle' } }
          ]
        },
        {
          id: 'jeronimos',
          name: { pt: 'Mosteiro dos Jerónimos', en: 'Jerónimos Monastery', fr: 'Monastère des Hiéronymites', es: 'Monasterio de los Jerónimos' },
          photos: [
            { file: 'Mosteiro dos Jerónimos 2012-11-25 1212.jpg', cap: { pt: 'Mosteiro dos Jerónimos, Belém', en: 'Jerónimos Monastery, Belém', fr: 'Monastère des Hiéronymites, Belém', es: 'Monasterio de los Jerónimos, Belém' } },
            { file: 'Padrão dos Descobrimentos 2012-11-14.jpg', cap: { pt: 'Padrão dos Descobrimentos', en: 'Monument to the Discoveries', fr: 'Monument des Découvertes', es: 'Padrón de los Descubrimientos' } }
          ]
        },
        {
          id: 'alfama',
          name: { pt: 'Alfama & elétricos', en: 'Alfama & trams', fr: 'Alfama et tramways', es: 'Alfama y tranvías' },
          photos: [
            { file: 'Lisbon tram 28 Alfama 09 2016 3324.jpg', cap: { pt: 'Elétrico 28 em Alfama', en: 'Tram 28 in Alfama', fr: 'Tram 28 à Alfama', es: 'Tranvía 28 en Alfama' } },
            { file: 'Alfama (Lisbon) September 2013-2.jpg', cap: { pt: 'Ruas de Alfama', en: 'Alfama streets', fr: 'Rues d’Alfama', es: 'Calles de Alfama' } }
          ]
        },
        {
          id: 'castelo',
          name: { pt: 'Castelo de São Jorge', en: 'São Jorge Castle', fr: 'Château Saint-Georges', es: 'Castillo de San Jorge' },
          photos: [
            { file: 'Castelo de São Jorge (Lisbon).jpg', cap: { pt: 'Castelo de São Jorge', en: 'São Jorge Castle', fr: 'Château Saint-Georges', es: 'Castillo de San Jorge' } },
            { file: 'Praça do Comércio (Lisbon, Portugal).jpg', cap: { pt: 'Praça do Comércio', en: 'Praça do Comércio', fr: 'Place du Commerce', es: 'Plaza del Comercio' } }
          ]
        }
      ]
    }
  ]
};

window.RUELAS.I18N = {
  pt: {
    brandSub: 'Transfers & Tours Lisboa',
    navHome: 'Início',
    navBook: 'Reservar',
    navTours: 'Tours',
    navFleet: 'Frota',
    navTrack: 'Seguir reserva',
    navAbout: 'A agência',
    navContact: 'Contacto',
    navMenu: 'Menu',
    callNow: 'Ligar',
    menuClose: 'Fechar',
    ctaBook: 'Reservar transfer',
    ctaTrack: 'Seguir',
    heroKicker: 'Lisboa · 24 horas',
    heroTitle: 'Transfers privados e tours a partir de Lisboa.',
    heroLead: 'Aeroporto, comboio, metro ou hotel. Motorista dedicado, preço claro, reserva em poucos minutos.',
    heroNote: 'Aberto ao público — qualquer viajante pode reservar.',
    bookTitle: 'Reservar um transfer',
    bookLead: 'Escolha o ponto de partida, o hotel de destino e os dados da viagem.',
    step1: 'Trajeto',
    step2: 'Veículo',
    step3: 'Extras',
    step4: 'Passageiro',
    step5: 'Confirmação',
    typeAh: 'Aeroporto → Hotel',
    typeHa: 'Hotel → Aeroporto',
    typeSh: 'Estação → Hotel',
    typeHs: 'Hotel → Estação',
    typeCustom: 'Outro trajeto',
    typeRt: 'Ida e volta',
    pickup: 'Ponto de partida',
    dropoff: 'Destino',
    hotelSearch: 'Pesquisar o nome do hotel',
    hotelPlaceholder: 'Clique para ver a lista completa, ou escreva o nome…',
    hotelNotListed: 'O hotel não está na lista — indicar a morada',
    hotelAddress: 'Morada do hotel / ponto de chegada',
    hotelAddressPh: 'Rua, número, código postal, cidade',
    room: 'Nº quarto (opcional)',
    date: 'Data',
    time: 'Hora',
    returnDate: 'Data de regresso',
    returnTime: 'Hora de regresso',
    flight: 'Nº de voo',
    pax: 'Passageiros',
    bags: 'Bagagens',
    nextVehicle: 'Escolher veículo',
    back: 'Voltar',
    continue: 'Continuar',
    vSedan: 'Berlina conforto',
    vVip: 'Berlina VIP',
    vVan: 'Minivan familiar',
    vSprinter: 'Minibus',
    vBadgeEco: 'Essencial',
    vBadgeVip: 'VIP',
    vBadgeFamily: 'Famílias',
    vBadgeGroup: 'Grupos',
    paxShort: 'pax',
    bagsShort: 'malas',
    fromPrice: 'a partir de',
    optBaby: 'Cadeira de bebé / elevador',
    optBabyDesc: 'Norma UE, 0–36 kg',
    optMeet: 'Recepção com placa',
    optMeetDesc: 'Motorista no hall de chegadas',
    optStop: 'Paragem extra',
    optStopDesc: 'Desvio curto no percurso',
    optRefresh: 'Água e refrescos',
    optRefreshDesc: 'A bordo',
    totalEst: 'Total estimado',
    passengerTitle: 'Dados do passageiro',
    firstName: 'Nome',
    lastName: 'Apelido',
    email: 'E-mail',
    phone: 'Telefone / WhatsApp',
    notes: 'Observações (opcional)',
    payNote: 'Pagamento ao motorista ou conforme indicação da agência. Receberá o número da reserva por e-mail quando o sistema estiver ligado.',
    submit: 'Confirmar reserva',
    required: 'Campo obrigatório',
    servicesKicker: 'Serviços',
    servicesTitle: 'Do aeroporto ao hotel, das estações aos tours.',
    s1t: 'Aeroporto LIS',
    s1d: 'Terminais 1 e 2. Acompanhamento de voo e espera em caso de atraso.',
    s2t: 'Comboio & metro',
    s2d: 'Oriente, Santa Apolónia, Sete Rios, Cais do Sodré, Rossio e principais estações de metro.',
    s3t: 'Hoteis de Lisboa',
    s3d: 'Lista pesquisável com morada (hotéis, guesthouses, hostels). Se não aparecer, escreva o nome e a morada.',
    s4t: 'Tours privados',
    s4d: 'Sintra, Cascais e Fátima — privativo ou em grupo, conforme a grelha.',
    toursKicker: 'Excursões',
    toursTitle: 'Sintra, Cascais, Fátima',
    toursLead: 'Tours internos da Agence Ruelas. A grelha de preços será confirmada com os dados oficiais da agência.',
    duration: 'Duração',
    hours: 'horas',
    privateHire: 'Privativo',
    shared: 'Grupo / partilhado',
    perPerson: '/ pessoa',
    minPax: 'mín.',
    bookTour: 'Reservar este tour',
    pricesNote: 'Preços indicativos — a grelha definitiva será atualizada com os dados da agência.',
    tourPickup: 'Recolha (hotel ou morada)',
    tourMode: 'Tipo',
    modePrivate: 'Privativo (veículo só para si)',
    modeShared: 'Grupo / partilhado',
    fleetKicker: 'Frota',
    fleetTitle: 'Veículos recentes, climatizados, condutores profissionais.',
    howKicker: 'Como funciona',
    howTitle: 'Reservar em quatro passos',
    h1t: 'Escolha o trajeto',
    h1d: 'Aeroporto, estação ou morada, e o hotel de destino.',
    h2t: 'Confirme os dados',
    h2d: 'Data, hora, voo, passageiros e veículo.',
    h3t: 'Receba o número',
    h3d: 'Guarde a referência RU- e o e-mail ou telefone usados na reserva.',
    h4t: 'Siga ou cancele',
    h4d: 'Consulte o estado no site ou contacte-nos com o número da reserva.',
    aboutKicker: 'A agência',
    aboutTitle: 'Agence Ruelas, Lisbonne.',
    aboutBody: 'Empresa de transfers e tours ao serviço de viajantes, hotéis e parceiros. Este site é a entrada pública: qualquer pessoa pode reservar. As reservas serão depois tratadas pela equipa da agência.',
    trackTitle: 'Seguir a reserva',
    trackLead: 'Indique o número da reserva e o e-mail ou o telefone usados no pedido.',
    trackRef: 'Número da reserva',
    trackEmail: 'E-mail da reserva',
    trackBtn: 'Consultar',
    trackNotFound: 'Reserva não encontrada. Verifique o número e o e-mail ou telefone.',
    status: 'Estado',
    stPendente: 'Pendente',
    stConfirmado: 'Confirmado',
    stCancelado: 'Cancelado',
    stRealizado: 'Realizado',
    stCancelReq: 'Cancelamento pedido',
    cancelBtn: 'Pedir cancelamento',
    cancelHint: 'Pode também ligar ou escrever no WhatsApp com o número da reserva.',
    cancelDone: 'Pedido de cancelamento registado. A agência confirmará.',
    voucherTitle: 'Reserva registada',
    voucherLead: 'Guarde este número. Use-o com o e-mail ou o telefone para seguir o estado.',
    printVoucher: 'Imprimir / guardar',
    newBooking: 'Nova reserva',
    kindTransfer: 'Transfer',
    kindTour: 'Tour',
    hotelLabel: 'Hotel',
    contactTitle: 'Contacto',
    contactLead: 'Equipa disponível para transfers e tours.',
    footerLegal: 'Agence Ruelas · Lisboa. Site público independente do portal interno.',
    groupAirports: 'Aeroporto',
    groupTrain: 'Comboio',
    groupMetro: 'Metro',
    noHotelMatch: 'Nenhum hotel com este nome — assinale “não está na lista”.',
    selectHotel: 'Selecione um hotel ou indique a morada.',
    whatsappMsg: 'Olá, gostaria de cancelar / informar sobre a reserva',
    summary: 'Resumo',
    include: 'Inclui'
  },
  en: {
    brandSub: 'Lisbon Transfers & Tours',
    navHome: 'Home',
    navBook: 'Book',
    navTours: 'Tours',
    navFleet: 'Fleet',
    navTrack: 'Track booking',
    navAbout: 'The agency',
    navContact: 'Contact',
    navMenu: 'Menu',
    callNow: 'Call',
    menuClose: 'Close',
    ctaBook: 'Book a transfer',
    ctaTrack: 'Track',
    heroKicker: 'Lisbon · 24/7',
    heroTitle: 'Private transfers and tours from Lisbon.',
    heroLead: 'Airport, train, metro or hotel. Dedicated driver, clear price, booked in minutes.',
    heroNote: 'Open to the public — anyone can book.',
    bookTitle: 'Book a transfer',
    bookLead: 'Choose pickup, your hotel, and trip details.',
    step1: 'Route',
    step2: 'Vehicle',
    step3: 'Extras',
    step4: 'Passenger',
    step5: 'Confirmation',
    typeAh: 'Airport → Hotel',
    typeHa: 'Hotel → Airport',
    typeSh: 'Station → Hotel',
    typeHs: 'Hotel → Station',
    typeCustom: 'Custom route',
    typeRt: 'Round trip',
    pickup: 'Pickup',
    dropoff: 'Drop-off',
    hotelSearch: 'Search hotel name',
    hotelPlaceholder: 'Click to scroll the full list, or type a name…',
    hotelNotListed: 'Hotel not in the list — enter the address',
    hotelAddress: 'Hotel address / arrival point',
    hotelAddressPh: 'Street, number, postcode, city',
    room: 'Room no. (optional)',
    date: 'Date',
    time: 'Time',
    returnDate: 'Return date',
    returnTime: 'Return time',
    flight: 'Flight no.',
    pax: 'Passengers',
    bags: 'Luggage',
    nextVehicle: 'Choose vehicle',
    back: 'Back',
    continue: 'Continue',
    vSedan: 'Comfort sedan',
    vVip: 'VIP sedan',
    vVan: 'Family minivan',
    vSprinter: 'Minibus',
    vBadgeEco: 'Essential',
    vBadgeVip: 'VIP',
    vBadgeFamily: 'Families',
    vBadgeGroup: 'Groups',
    paxShort: 'pax',
    bagsShort: 'bags',
    fromPrice: 'from',
    optBaby: 'Baby / booster seat',
    optBabyDesc: 'EU standard, 0–36 kg',
    optMeet: 'Meet & greet sign',
    optMeetDesc: 'Driver at arrivals hall',
    optStop: 'Extra stop',
    optStopDesc: 'Short detour on the way',
    optRefresh: 'Water & refreshments',
    optRefreshDesc: 'On board',
    totalEst: 'Estimated total',
    passengerTitle: 'Passenger details',
    firstName: 'First name',
    lastName: 'Last name',
    email: 'Email',
    phone: 'Phone / WhatsApp',
    notes: 'Notes (optional)',
    payNote: 'Pay the driver or as advised by the agency. You will receive the booking number by email once the system is connected.',
    submit: 'Confirm booking',
    required: 'Required field',
    servicesKicker: 'Services',
    servicesTitle: 'Airport to hotel, stations to tours.',
    s1t: 'LIS Airport',
    s1d: 'Terminals 1 and 2. Flight monitoring and wait time if delayed.',
    s2t: 'Train & metro',
    s2d: 'Oriente, Santa Apolónia, Sete Rios, Cais do Sodré, Rossio and main metro stations.',
    s3t: 'Lisbon hotels',
    s3d: 'Searchable list with address (hotels, guesthouses, hostels). If missing, type the name and address.',
    s4t: 'Private tours',
    s4d: 'Sintra, Cascais and Fátima — private hire or shared, as per the table.',
    toursKicker: 'Excursions',
    toursTitle: 'Sintra, Cascais, Fátima',
    toursLead: 'In-house tours by Agence Ruelas. Final prices will be updated with the agency’s official grid.',
    duration: 'Duration',
    hours: 'hours',
    privateHire: 'Private',
    shared: 'Shared / group',
    perPerson: '/ person',
    minPax: 'min.',
    bookTour: 'Book this tour',
    pricesNote: 'Indicative prices — the final grid will be updated with agency data.',
    tourPickup: 'Pickup (hotel or address)',
    tourMode: 'Type',
    modePrivate: 'Private (vehicle just for you)',
    modeShared: 'Shared / group',
    fleetKicker: 'Fleet',
    fleetTitle: 'Recent vehicles, air-conditioned, professional drivers.',
    howKicker: 'How it works',
    howTitle: 'Book in four steps',
    h1t: 'Choose the route',
    h1d: 'Airport, station or address, and your hotel.',
    h2t: 'Confirm details',
    h2d: 'Date, time, flight, passengers and vehicle.',
    h3t: 'Keep your number',
    h3d: 'Save the RU- reference and the email or phone used to book.',
    h4t: 'Track or cancel',
    h4d: 'Check status on the site or contact us with your booking number.',
    aboutKicker: 'The agency',
    aboutTitle: 'Agence Ruelas, Lisbon.',
    aboutBody: 'Transfers and tours for travellers, hotels and partners. This website is the public entrance: anyone can book. Bookings are then handled by the agency team.',
    trackTitle: 'Track your booking',
    trackLead: 'Enter the booking number and the email or phone used when you booked.',
    trackRef: 'Booking number',
    trackEmail: 'Booking email',
    trackBtn: 'Look up',
    trackNotFound: 'Booking not found. Check the number and the email or phone.',
    status: 'Status',
    stPendente: 'Pending',
    stConfirmado: 'Confirmed',
    stCancelado: 'Cancelled',
    stRealizado: 'Completed',
    stCancelReq: 'Cancellation requested',
    cancelBtn: 'Request cancellation',
    cancelHint: 'You can also call or WhatsApp us with your booking number.',
    cancelDone: 'Cancellation request saved. The agency will confirm.',
    voucherTitle: 'Booking recorded',
    voucherLead: 'Keep this number. Use it with your email or phone to track status.',
    printVoucher: 'Print / save',
    newBooking: 'New booking',
    kindTransfer: 'Transfer',
    kindTour: 'Tour',
    hotelLabel: 'Hotel',
    contactTitle: 'Contact',
    contactLead: 'Team available for transfers and tours.',
    footerLegal: 'Agence Ruelas · Lisbon. Public site, independent from the staff portal.',
    groupAirports: 'Airport',
    groupTrain: 'Train',
    groupMetro: 'Metro',
    noHotelMatch: 'No hotel with this name — tick “not in the list”.',
    selectHotel: 'Select a hotel or enter the address.',
    whatsappMsg: 'Hello, I would like to cancel / ask about booking',
    summary: 'Summary',
    include: 'Includes'
  },
  fr: {
    brandSub: 'Transfers & Tours Lisbonne',
    navHome: 'Accueil',
    navBook: 'Réserver',
    navTours: 'Tours',
    navFleet: 'Flotte',
    navTrack: 'Suivre ma résa',
    navAbout: 'L’agence',
    navContact: 'Contact',
    navMenu: 'Menu',
    callNow: 'Appeler',
    menuClose: 'Fermer',
    ctaBook: 'Réserver un transfer',
    ctaTrack: 'Suivi',
    heroKicker: 'Lisbonne · 24h/24',
    heroTitle: 'Transfers privés et tours au départ de Lisbonne.',
    heroLead: 'Aéroport, train, métro ou hôtel. Chauffeur dédié, tarif clair, réservation en quelques minutes.',
    heroNote: 'Ouvert au public — tout voyageur peut réserver.',
    bookTitle: 'Réserver un transfer',
    bookLead: 'Choisissez le départ, l’hôtel d’arrivée et les détails du trajet.',
    step1: 'Trajet',
    step2: 'Véhicule',
    step3: 'Extras',
    step4: 'Passager',
    step5: 'Confirmation',
    typeAh: 'Aéroport → Hôtel',
    typeHa: 'Hôtel → Aéroport',
    typeSh: 'Gare / métro → Hôtel',
    typeHs: 'Hôtel → Gare / métro',
    typeCustom: 'Autre trajet',
    typeRt: 'Aller-retour',
    pickup: 'Prise en charge',
    dropoff: 'Destination',
    hotelSearch: 'Rechercher le nom de l’hôtel',
    hotelPlaceholder: 'Cliquez pour parcourir toute la liste, ou tapez un nom…',
    hotelNotListed: 'L’hôtel n’est pas dans la liste — indiquer l’adresse',
    hotelAddress: 'Adresse de l’hôtel / point d’arrivée',
    hotelAddressPh: 'Rue, numéro, code postal, ville',
    room: 'N° de chambre (optionnel)',
    date: 'Date',
    time: 'Heure',
    returnDate: 'Date retour',
    returnTime: 'Heure retour',
    flight: 'N° de vol',
    pax: 'Passagers',
    bags: 'Bagages',
    nextVehicle: 'Choisir le véhicule',
    back: 'Retour',
    continue: 'Continuer',
    vSedan: 'Berline confort',
    vVip: 'Berline VIP',
    vVan: 'Minivan familial',
    vSprinter: 'Minibus',
    vBadgeEco: 'Essentiel',
    vBadgeVip: 'VIP',
    vBadgeFamily: 'Familles',
    vBadgeGroup: 'Groupes',
    paxShort: 'pax',
    bagsShort: 'bagages',
    fromPrice: 'à partir de',
    optBaby: 'Siège bébé / rehausseur',
    optBabyDesc: 'Norme UE, 0–36 kg',
    optMeet: 'Accueil avec pancarte',
    optMeetDesc: 'Chauffeur au hall d’arrivées',
    optStop: 'Arrêt supplémentaire',
    optStopDesc: 'Court détour sur le trajet',
    optRefresh: 'Eau et rafraîchissements',
    optRefreshDesc: 'À bord',
    totalEst: 'Total estimé',
    passengerTitle: 'Coordonnées du passager',
    firstName: 'Prénom',
    lastName: 'Nom',
    email: 'E-mail',
    phone: 'Téléphone / WhatsApp',
    notes: 'Remarques (optionnel)',
    payNote: 'Règlement au chauffeur ou selon les consignes de l’agence. Le n° de réservation sera aussi envoyé par e-mail une fois le système connecté.',
    submit: 'Confirmer la réservation',
    required: 'Champ obligatoire',
    servicesKicker: 'Services',
    servicesTitle: 'De l’aéroport à l’hôtel, des gares aux tours.',
    s1t: 'Aéroport LIS',
    s1d: 'Terminaux 1 et 2. Suivi de vol et attente en cas de retard.',
    s2t: 'Train & métro',
    s2d: 'Oriente, Santa Apolónia, Sete Rios, Cais do Sodré, Rossio et principales stations de métro.',
    s3t: 'Hôtels de Lisbonne',
    s3d: 'Liste recherchable. Si l’hôtel n’apparaît pas, indiquez l’adresse.',
    s4t: 'Tours privés',
    s4d: 'Sintra, Cascais et Fátima — privatisé ou en groupe, selon la grille.',
    toursKicker: 'Excursions',
    toursTitle: 'Sintra, Cascais, Fátima',
    toursLead: 'Tours internes Agence Ruelas. La grille tarifaire sera confirmée avec les données officielles de l’agence.',
    duration: 'Durée',
    hours: 'heures',
    privateHire: 'Privatisé',
    shared: 'Groupe / partagé',
    perPerson: '/ pers.',
    minPax: 'min.',
    bookTour: 'Réserver ce tour',
    pricesNote: 'Tarifs indicatifs — la grille définitive sera mise à jour avec les données de l’agence.',
    tourPickup: 'Prise en charge (hôtel ou adresse)',
    tourMode: 'Type',
    modePrivate: 'Privatisé (véhicule pour vous seuls)',
    modeShared: 'Groupe / partagé',
    fleetKicker: 'Flotte',
    fleetTitle: 'Véhicules récents, climatisés, chauffeurs professionnels.',
    howKicker: 'Fonctionnement',
    howTitle: 'Réserver en quatre étapes',
    h1t: 'Choisissez le trajet',
    h1d: 'Aéroport, gare ou adresse, et l’hôtel de destination.',
    h2t: 'Confirmez les détails',
    h2d: 'Date, heure, vol, passagers et véhicule.',
    h3t: 'Gardez le numéro',
    h3d: 'Conservez la référence RU- et l’e-mail ou le téléphone utilisés.',
    h4t: 'Suivez ou annulez',
    h4d: 'Consultez l’état sur le site ou contactez-nous avec le n° de réservation.',
    aboutKicker: 'L’agence',
    aboutTitle: 'Agence Ruelas, Lisbonne.',
    aboutBody: 'Transfers et tours pour voyageurs, hôtels et partenaires. Ce site est l’entrée publique : chacun peut réserver. Les demandes sont ensuite traitées par l’équipe de l’agence.',
    trackTitle: 'Suivre la réservation',
    trackLead: 'Indiquez le numéro de réservation et l’e-mail ou le téléphone utilisés lors de la demande.',
    trackRef: 'Numéro de réservation',
    trackEmail: 'E-mail de la réservation',
    trackBtn: 'Consulter',
    trackNotFound: 'Réservation introuvable. Vérifiez le numéro et l’e-mail ou le téléphone.',
    status: 'Statut',
    stPendente: 'En attente',
    stConfirmado: 'Confirmée',
    stCancelado: 'Annulée',
    stRealizado: 'Effectuée',
    stCancelReq: 'Annulation demandée',
    cancelBtn: 'Demander l’annulation',
    cancelHint: 'Vous pouvez aussi appeler ou écrire sur WhatsApp avec le numéro de réservation.',
    cancelDone: 'Demande d’annulation enregistrée. L’agence confirmera.',
    voucherTitle: 'Réservation enregistrée',
    voucherLead: 'Conservez ce numéro. Utilisez-le avec votre e-mail ou votre téléphone pour suivre l’état.',
    printVoucher: 'Imprimer / enregistrer',
    newBooking: 'Nouvelle réservation',
    kindTransfer: 'Transfer',
    kindTour: 'Tour',
    hotelLabel: 'Hôtel',
    contactTitle: 'Contact',
    contactLead: 'Équipe disponible pour transfers et tours.',
    footerLegal: 'Agence Ruelas · Lisbonne. Site public, indépendant du portail interne.',
    groupAirports: 'Aéroport',
    groupTrain: 'Train',
    groupMetro: 'Métro',
    noHotelMatch: 'Aucun hôtel à ce nom — cochez « pas dans la liste ».',
    selectHotel: 'Sélectionnez un hôtel ou indiquez l’adresse.',
    whatsappMsg: 'Bonjour, je souhaite annuler / m’informer sur la réservation',
    summary: 'Récapitulatif',
    include: 'Inclus'
  },
  es: {
    brandSub: 'Traslados y Tours Lisboa',
    navHome: 'Inicio',
    navBook: 'Reservar',
    navTours: 'Tours',
    navFleet: 'Flota',
    navTrack: 'Seguir reserva',
    navAbout: 'La agencia',
    navContact: 'Contacto',
    navMenu: 'Menú',
    callNow: 'Llamar',
    menuClose: 'Cerrar',
    ctaBook: 'Reservar traslado',
    ctaTrack: 'Seguir',
    heroKicker: 'Lisboa · 24 horas',
    heroTitle: 'Traslados privados y tours desde Lisboa.',
    heroLead: 'Aeropuerto, tren, metro u hotel. Chófer dedicado, precio claro, reserva en minutos.',
    heroNote: 'Abierto al público — cualquier viajero puede reservar.',
    bookTitle: 'Reservar un traslado',
    bookLead: 'Elija salida, hotel de destino y datos del viaje.',
    step1: 'Trayecto',
    step2: 'Vehículo',
    step3: 'Extras',
    step4: 'Pasajero',
    step5: 'Confirmación',
    typeAh: 'Aeropuerto → Hotel',
    typeHa: 'Hotel → Aeropuerto',
    typeSh: 'Estación → Hotel',
    typeHs: 'Hotel → Estación',
    typeCustom: 'Otro trayecto',
    typeRt: 'Ida y vuelta',
    pickup: 'Recogida',
    dropoff: 'Destino',
    hotelSearch: 'Buscar el nombre del hotel',
    hotelPlaceholder: 'Pulse para ver la lista completa, o escriba el nombre…',
    hotelNotListed: 'El hotel no está en la lista — indicar la dirección',
    hotelAddress: 'Dirección del hotel / punto de llegada',
    hotelAddressPh: 'Calle, número, código postal, ciudad',
    room: 'Nº habitación (opcional)',
    date: 'Fecha',
    time: 'Hora',
    returnDate: 'Fecha de regreso',
    returnTime: 'Hora de regreso',
    flight: 'Nº de vuelo',
    pax: 'Pasajeros',
    bags: 'Equipaje',
    nextVehicle: 'Elegir vehículo',
    back: 'Volver',
    continue: 'Continuar',
    vSedan: 'Berlina confort',
    vVip: 'Berlina VIP',
    vVan: 'Minivan familiar',
    vSprinter: 'Minibús',
    vBadgeEco: 'Esencial',
    vBadgeVip: 'VIP',
    vBadgeFamily: 'Familias',
    vBadgeGroup: 'Grupos',
    paxShort: 'pax',
    bagsShort: 'maletas',
    fromPrice: 'desde',
    optBaby: 'Silla de bebé / alzador',
    optBabyDesc: 'Norma UE, 0–36 kg',
    optMeet: 'Recepción con cartel',
    optMeetDesc: 'Chófer en llegadas',
    optStop: 'Parada extra',
    optStopDesc: 'Desvío corto en la ruta',
    optRefresh: 'Agua y refrescos',
    optRefreshDesc: 'A bordo',
    totalEst: 'Total estimado',
    passengerTitle: 'Datos del pasajero',
    firstName: 'Nombre',
    lastName: 'Apellidos',
    email: 'Correo',
    phone: 'Teléfono / WhatsApp',
    notes: 'Notas (opcional)',
    payNote: 'Pago al chófer o según indique la agencia. Recibirá el número de reserva por correo cuando el sistema esté conectado.',
    submit: 'Confirmar reserva',
    required: 'Campo obligatorio',
    servicesKicker: 'Servicios',
    servicesTitle: 'Del aeropuerto al hotel, de las estaciones a los tours.',
    s1t: 'Aeropuerto LIS',
    s1d: 'Terminales 1 y 2. Seguimiento de vuelo y espera si hay retraso.',
    s2t: 'Tren y metro',
    s2d: 'Oriente, Santa Apolónia, Sete Rios, Cais do Sodré, Rossio y principales estaciones de metro.',
    s3t: 'Hoteles de Lisboa',
    s3d: 'Lista con búsqueda. Si el hotel no aparece, indique la dirección.',
    s4t: 'Tours privados',
    s4d: 'Sintra, Cascais y Fátima — privado o en grupo, según la tarifa.',
    toursKicker: 'Excursiones',
    toursTitle: 'Sintra, Cascais, Fátima',
    toursLead: 'Tours internos de Agence Ruelas. La tarifa se confirmará con los datos oficiales de la agencia.',
    duration: 'Duración',
    hours: 'horas',
    privateHire: 'Privado',
    shared: 'Grupo / compartido',
    perPerson: '/ pers.',
    minPax: 'mín.',
    bookTour: 'Reservar este tour',
    pricesNote: 'Precios orientativos — la tarifa definitiva se actualizará con los datos de la agencia.',
    tourPickup: 'Recogida (hotel o dirección)',
    tourMode: 'Tipo',
    modePrivate: 'Privado (vehículo solo para ustedes)',
    modeShared: 'Grupo / compartido',
    fleetKicker: 'Flota',
    fleetTitle: 'Vehículos recientes, climatizados, conductores profesionales.',
    howKicker: 'Cómo funciona',
    howTitle: 'Reservar en cuatro pasos',
    h1t: 'Elija el trayecto',
    h1d: 'Aeropuerto, estación o dirección, y el hotel.',
    h2t: 'Confirme los datos',
    h2d: 'Fecha, hora, vuelo, pasajeros y vehículo.',
    h3t: 'Guarde el número',
    h3d: 'Conserve la referencia RU- y el correo o teléfono usados.',
    h4t: 'Siga o cancele',
    h4d: 'Consulte el estado en la web o contáctenos con el número de reserva.',
    aboutKicker: 'La agencia',
    aboutTitle: 'Agence Ruelas, Lisboa.',
    aboutBody: 'Traslados y tours para viajeros, hoteles y socios. Este sitio es la entrada pública: cualquiera puede reservar. Luego las gestiona el equipo de la agencia.',
    trackTitle: 'Seguir la reserva',
    trackLead: 'Indique el número de reserva y el correo o el teléfono usados en la solicitud.',
    trackRef: 'Número de reserva',
    trackEmail: 'Correo de la reserva',
    trackBtn: 'Consultar',
    trackNotFound: 'Reserva no encontrada. Compruebe el número y el correo o teléfono.',
    status: 'Estado',
    stPendente: 'Pendiente',
    stConfirmado: 'Confirmada',
    stCancelado: 'Cancelada',
    stRealizado: 'Realizada',
    stCancelReq: 'Cancelación pedida',
    cancelBtn: 'Pedir cancelación',
    cancelHint: 'También puede llamar o escribir por WhatsApp con el número de reserva.',
    cancelDone: 'Solicitud de cancelación registrada. La agencia confirmará.',
    voucherTitle: 'Reserva registrada',
    voucherLead: 'Guarde este número. Úselo con su correo o teléfono para seguir el estado.',
    printVoucher: 'Imprimir / guardar',
    newBooking: 'Nueva reserva',
    kindTransfer: 'Traslado',
    kindTour: 'Tour',
    hotelLabel: 'Hotel',
    contactTitle: 'Contacto',
    contactLead: 'Equipo disponible para traslados y tours.',
    footerLegal: 'Agence Ruelas · Lisboa. Sitio público, independiente del portal interno.',
    groupAirports: 'Aeropuerto',
    groupTrain: 'Tren',
    groupMetro: 'Metro',
    noHotelMatch: 'Ningún hotel con ese nombre — marque “no está en la lista”.',
    selectHotel: 'Seleccione un hotel o indique la dirección.',
    whatsappMsg: 'Hola, quisiera cancelar / consultar la reserva',
    summary: 'Resumen',
    include: 'Incluye'
  }
};

(function mergeI18n() {
  const extra = {
    pt: {
      pickupManual: 'Indicar o ponto de partida manualmente (nome + morada)',
      destManualHint: 'Se o hotel / casa não estiver na lista, escreva o nome e a morada.',
      contactNeeded: 'Contacto obrigatório (telefone e e-mail)',
      emailReq: 'E-mail *',
      phoneReq: 'Telefone / WhatsApp *',
      hotelCount: 'alojamentos em Lisboa na lista',
      accountBtn: 'Conta',
      login: 'Entrar',
      register: 'Criar conta',
      logout: 'Sair',
      myBookings: 'As minhas reservas',
      password: 'Palavra-passe',
      createAccount: 'Criar conta para guardar o histórico',
      accountOk: 'Conta criada. As suas reservas ficam associadas a este e-mail.',
      requiredBoth: 'Telefone e e-mail são obrigatórios.',
      placesTitle: 'Sítios a visitar',
      placesKicker: 'Galeria',
      noAccountBookings: 'Ainda não há reservas nesta conta.',
      hotelNamePh: 'Nome do hotel / casa / morada',
      seePhotos: 'Ver todas as fotos',
      photos: 'fotos',
      photoOf: 'de',
      closeGallery: 'Fechar',
      placesLead: 'Galeria de cada paragem: Palácio da Pena, Cabo da Roca, Fátima, Belém, Alfama e mais. Clique para percorrer todas as vistas.',
      nextPhoto: 'Seguinte',
      prevPhoto: 'Anterior',
      stopsLabel: 'paragens',
      photoCredit: 'Fotografias Wikimedia Commons (licenças livres).',
      galleryKeys: 'Zoom: + − · pinça / moleta · Esc fecha',
      hotelScroll: 'deslize para ver todos',
      trackPhone: 'Telefone / WhatsApp da reserva',
      trackOr: 'Basta um: e-mail ou telefone, juntamente com o número da reserva.',
      trackNeedContact: 'Indique o número da reserva e o e-mail ou o telefone.'
    },
    en: {
      pickupManual: 'Enter pickup manually (name + address)',
      destManualHint: 'If the hotel / house is not listed, type the name and address.',
      contactNeeded: 'Required contact (phone and email)',
      emailReq: 'Email *',
      phoneReq: 'Phone / WhatsApp *',
      hotelCount: 'Lisbon stays in the list',
      accountBtn: 'Account',
      login: 'Log in',
      register: 'Create account',
      logout: 'Log out',
      myBookings: 'My bookings',
      password: 'Password',
      createAccount: 'Create an account to keep your booking history',
      accountOk: 'Account created. Your bookings stay linked to this email.',
      requiredBoth: 'Phone and email are required.',
      placesTitle: 'Places to visit',
      placesKicker: 'Gallery',
      noAccountBookings: 'No bookings on this account yet.',
      hotelNamePh: 'Hotel / house / address name',
      seePhotos: 'See all photos',
      photos: 'photos',
      photoOf: 'of',
      closeGallery: 'Close',
      placesLead: 'A photo gallery for every stop: Pena Palace, Cabo da Roca, Fátima, Belém, Alfama and more. Click to browse every view.',
      nextPhoto: 'Next',
      prevPhoto: 'Previous',
      stopsLabel: 'stops',
      photoCredit: 'Photographs from Wikimedia Commons (free licences).',
      galleryKeys: 'Zoom: + − · pinch / scroll · Esc to close',
      hotelScroll: 'scroll to see all',
      trackPhone: 'Booking phone / WhatsApp',
      trackOr: 'Only one is needed: email or phone, together with the booking number.',
      trackNeedContact: 'Enter the booking number and either the email or the phone.'
    },
    fr: {
      pickupManual: 'Saisir le départ manuellement (nom + adresse)',
      destManualHint: 'Si l’hôtel / la maison n’est pas dans la liste, indiquez le nom et l’adresse.',
      contactNeeded: 'Contact obligatoire (téléphone et e-mail)',
      emailReq: 'E-mail *',
      phoneReq: 'Téléphone / WhatsApp *',
      hotelCount: 'hébergements à Lisbonne dans la liste',
      accountBtn: 'Compte',
      login: 'Connexion',
      register: 'Créer un compte',
      logout: 'Déconnexion',
      myBookings: 'Mes réservations',
      password: 'Mot de passe',
      createAccount: 'Créer un compte pour garder l’historique',
      accountOk: 'Compte créé. Vos réservations restent liées à cet e-mail.',
      requiredBoth: 'Le téléphone et l’e-mail sont obligatoires.',
      placesTitle: 'Lieux à visiter',
      placesKicker: 'Galerie',
      noAccountBookings: 'Aucune réservation sur ce compte.',
      hotelNamePh: 'Nom de l’hôtel / maison / adresse',
      seePhotos: 'Voir toutes les photos',
      photos: 'photos',
      photoOf: 'sur',
      closeGallery: 'Fermer',
      placesLead: 'Galerie de chaque étape : palais de Pena, Cabo da Roca, Fátima, Belém, Alfama… Cliquez pour parcourir toutes les vues.',
      nextPhoto: 'Suivante',
      prevPhoto: 'Précédente',
      stopsLabel: 'étapes',
      photoCredit: 'Photographies Wikimedia Commons (licences libres).',
      galleryKeys: 'Zoom : + − · pince / molette · Échap pour fermer',
      hotelScroll: 'faites défiler pour tout voir',
      trackPhone: 'Téléphone / WhatsApp de la réservation',
      trackOr: 'Un seul suffit : e-mail ou téléphone, avec le numéro de réservation.',
      trackNeedContact: 'Indiquez le numéro de réservation et l’e-mail ou le téléphone.'
    },
    es: {
      pickupManual: 'Indicar la salida manualmente (nombre + dirección)',
      destManualHint: 'Si el hotel / casa no está en la lista, escriba el nombre y la dirección.',
      contactNeeded: 'Contacto obligatorio (teléfono y correo)',
      emailReq: 'Correo *',
      phoneReq: 'Teléfono / WhatsApp *',
      hotelCount: 'alojamientos en Lisboa en la lista',
      accountBtn: 'Cuenta',
      login: 'Entrar',
      register: 'Crear cuenta',
      logout: 'Salir',
      myBookings: 'Mis reservas',
      password: 'Contraseña',
      createAccount: 'Crear cuenta para guardar el historial',
      accountOk: 'Cuenta creada. Sus reservas quedan ligadas a este correo.',
      requiredBoth: 'Teléfono y correo son obligatorios.',
      placesTitle: 'Sitios a visitar',
      placesKicker: 'Galería',
      noAccountBookings: 'Aún no hay reservas en esta cuenta.',
      hotelNamePh: 'Nombre del hotel / casa / dirección',
      seePhotos: 'Ver todas las fotos',
      photos: 'fotos',
      photoOf: 'de',
      closeGallery: 'Cerrar',
      placesLead: 'Galería de cada parada: Palacio de Pena, Cabo da Roca, Fátima, Belém, Alfama y más. Pulse para ver todas las vistas.',
      nextPhoto: 'Siguiente',
      prevPhoto: 'Anterior',
      stopsLabel: 'paradas',
      photoCredit: 'Fotografías Wikimedia Commons (licencias libres).',
      galleryKeys: 'Zoom: + − · pellizco / rueda · Esc para cerrar',
      hotelScroll: 'deslice para ver todos',
      trackPhone: 'Teléfono / WhatsApp de la reserva',
      trackOr: 'Basta uno: correo o teléfono, junto con el número de reserva.',
      trackNeedContact: 'Indique el número de reserva y el correo o el teléfono.'
    }
  };
  Object.keys(extra).forEach(function (lang) {
    Object.assign(window.RUELAS.I18N[lang], extra[lang]);
  });
})();
