/* Catalogue Lisbonne — hôtels, boutiques, residenciais, guesthouses, hostels, aparthotels.
   Si le logement n’y figure pas, le client saisit le nom + l’adresse. */
window.RUELAS.HOTELS = [
  { id:'h001', name:'Four Seasons Hotel Ritz Lisboa', aka:'Four Seasons Hotel Ritz Lisbon', area:'Avenidas Novas', address:'Rua Rodrigo da Fonseca 88, 1099-039 Lisboa', cat:'5' },
  { id:'h002', name:'Tivoli Avenida Liberdade Lisboa', aka:'Tivoli Avenida da Liberdade Lisboa', area:'Avenida da Liberdade', address:'Avenida da Liberdade 185, 1269-050 Lisboa', cat:'5' },
  { id:'h003', name:'Tivoli Oriente Lisboa', area:'Parque das Nações', address:'Avenida D. João II, Parque das Nações, 1990-083 Lisboa', cat:'4' },
  { id:'h004', name:'Corinthia Lisbon', aka:'Corinthia Hotel Lisbon', area:'Praça de Espanha', address:'Avenida Columbano Bordalo Pinheiro 105, 1099-031 Lisboa', cat:'5' },
  { id:'h005', name:'EPIC SANA Marquês', area:'Marquês de Pombal', address:'Avenida Engenheiro Duarte Pacheco 24, 1070-110 Lisboa', cat:'5' },
  { id:'h006', name:'EPIC SANA Lisboa Hotel', aka:'EPIC SANA Lisboa', area:'Parque Eduardo VII', address:'Avenida Eduardo VII s/n, 1050-171 Lisboa', cat:'5' },
  { id:'h007', name:'Sheraton Lisboa Hotel & Spa', area:'Parque', address:'Rua Latino Coelho 1, 1069-025 Lisboa', cat:'5' },
  { id:'h008', name:'Pestana Palace Lisboa Hotel & National Monument', aka:'Pestana Palace Lisboa', area:'Alcântara', address:'Rua Jau 54, 1300-314 Lisboa', cat:'5' },
  { id:'h009', name:'Pestana CR7 Lisboa', area:'Baixa', address:'Rua do Comércio 54, 1100-150 Lisboa', cat:'4' },
  { id:'h010', name:'Pestana Rua Augusta', area:'Baixa', address:'Rua Augusta 2, 1100-053 Lisboa', cat:'4' },
  { id:'h011', name:'Altis Grand Hotel', area:'Avenida da Liberdade', address:'Rua Castilho 11, 1269-072 Lisboa', cat:'5' },
  { id:'h012', name:'Altis Avenida Hotel', area:'Restauradores', address:'Rua 1.º de Dezembro 120, 1200-359 Lisboa', cat:'5' },
  { id:'h013', name:'Altis Belém Hotel & Spa', area:'Belém', address:'Doca do Bom Sucesso, 1400-038 Lisboa', cat:'5' },
  { id:'h014', name:'Altis Prime', area:'Avenida da Liberdade', address:'Rua Manutenção Militar 2, 1250-137 Lisboa', cat:'4' },
  { id:'h015', name:'Memmo Alfama', area:'Alfama', address:'Travessa das Merceeiras 27, 1100-348 Lisboa', cat:'4' },
  { id:'h016', name:'Memmo Príncipe Real', area:'Príncipe Real', address:'Rua Dom Pedro V 56, 1250-094 Lisboa', cat:'5' },
  { id:'h017', name:'Bairro Alto Hotel', area:'Chiado', address:'Praça Luís de Camões 2, 1200-243 Lisboa', cat:'5' },
  { id:'h018', name:'The One Palácio da Anunciada', aka:'Palácio da Anunciada', area:'Príncipe Real', address:'Rua da Anunciada 152, 1150-013 Lisboa', cat:'5' },
  { id:'h019', name:'Palácio Ludovice Wine Experience Hotel', area:'Bairro Alto', address:'Rua de São Pedro de Alcântara 39, 1250-237 Lisboa', cat:'5' },
  { id:'h020', name:'Avenida Palace Hotel', aka:'Hotel Avenida Palace', area:'Restauradores', address:'Rua 1.º de Dezembro 123, 1200-360 Lisboa', cat:'5' },
  { id:'h021', name:'InterContinental Lisbon', area:'Saldanha', address:'Rua Castilho 149, 1099-034 Lisboa', cat:'5' },
  { id:'h022', name:'Sofitel Lisbon Liberdade', area:'Avenida da Liberdade', address:'Avenida da Liberdade 127, 1269-038 Lisboa', cat:'5' },
  { id:'h023', name:'Olissippo Lapa Palace', area:'Lapa', address:'Rua do Pau de Bandeira 4, 1249-021 Lisboa', cat:'5' },
  { id:'h024', name:'Olissippo Castelo', area:'Castelo', address:'Rua Costa do Castelo 112, 1100-179 Lisboa', cat:'4' },
  { id:'h025', name:'Olissippo Marquês de Sá', area:'Saldanha', address:'Avenida Miguel Bombarda 130, 1050-167 Lisboa', cat:'4' },
  { id:'h026', name:'Olissippo Oriente Hotel', aka:'Olissippo Oriente', area:'Parque das Nações', address:'Avenida Dom João II, Lote 1.16.01/02, 1990-083 Lisboa', cat:'4' },
  { id:'h027', name:'Valverde Hotel', area:'Avenida da Liberdade', address:'Avenida da Liberdade 164, 1250-146 Lisboa', cat:'5' },
  { id:'h028', name:'The Lumiares Hotel & Spa', area:'Bairro Alto', address:'Rua do Diário de Notícias 142, 1200-146 Lisboa', cat:'5' },
  { id:'h029', name:'Santiago de Alfama', aka:'Santiago de Alfama Boutique Hotel', area:'Alfama', address:'Rua de Santiago 10-14, 1100-494 Lisboa', cat:'5' },
  { id:'h030', name:'Solar do Castelo', area:'Castelo', address:'Rua das Cozinhas 2, 1100-181 Lisboa', cat:'4' },
  { id:'h031', name:'Myriad by SANA Hotels', aka:'Myriad by SANA', area:'Parque das Nações', address:'Cais das Naus, Lote 2.21.01, 1990-173 Lisboa', cat:'5' },
  { id:'h032', name:'SANA Lisboa Hotel', aka:'Sana Lisboa Hotel', area:'Saldanha', address:'Avenida Fontes Pereira de Melo 8, 1050-121 Lisboa', cat:'4' },
  { id:'h033', name:'SANA Metropolitan', area:'Saldanha', address:'Rua Soeiro Pereira Gomes 7, 1600-198 Lisboa', cat:'4' },
  { id:'h034', name:'SANA Malhoa', area:'Praça de Espanha', address:'Avenida José Malhoa 8, 1099-089 Lisboa', cat:'4' },
  { id:'h035', name:'SANA Reno', area:'Saldanha', address:'Avenida Duque de Ávila 195, 1050-082 Lisboa', cat:'3' },
  { id:'h036', name:'SANA Rex', area:'Saldanha', address:'Rua Castilho 169, 1070-051 Lisboa', cat:'3' },
  { id:'h037', name:'SANA Capitol', area:'Marquês de Pombal', address:'Rua Eça de Queirós 24, 1050-096 Lisboa', cat:'3' },
  { id:'h038', name:'NH Collection Lisboa Liberdade', area:'Avenida da Liberdade', address:'Avenida da Liberdade 180B, 1250-146 Lisboa', cat:'4' },
  { id:'h039', name:'NH Lisboa Campo Grande', aka:'NH Campo Grande', area:'Campo Grande', address:'Campo Grande 137, 1700-089 Lisboa', cat:'4' },
  { id:'h040', name:'Radisson Blu Lisbon', area:'Parque das Nações', address:'Avenida Marechal Gomes da Costa 13, 1800-255 Lisboa', cat:'4' },
  { id:'h041', name:'Marriott Lisbon Hotel', aka:'Lisbon Marriott Hotel', area:'Sete Rios', address:'Avenida dos Combatentes 45, 1600-042 Lisboa', cat:'4' },
  { id:'h042', name:'Renaissance Lisbon Hotel', area:'Avenida da Liberdade', address:'Avenida da Liberdade 120, 1269-053 Lisboa', cat:'4' },
  { id:'h043', name:'DoubleTree by Hilton Lisbon Fontana Park', area:'Saldanha', address:'Rua Engenheiro Vieira da Silva 2, 1050-105 Lisboa', cat:'4' },
  { id:'h044', name:'Hilton Garden Inn Lisbon Baixa', area:'Baixa', address:'Avenida Almirante Reis 31B, 1150-011 Lisboa', cat:'4' },
  { id:'h045', name:'Dom Pedro Palace', area:'Marquês de Pombal', address:'Avenida Engenheiro Duarte Pacheco 24, 1070-109 Lisboa', cat:'5' },
  { id:'h046', name:'Inspira Santa Marta Hotel', aka:'Inspira Liberdade Boutique Hotel', area:'Avenida da Liberdade', address:'Rua de Santa Marta 48, 1150-297 Lisboa', cat:'4' },
  { id:'h047', name:'LX Boutique Hotel', area:'Cais do Sodré', address:'Rua do Alecrim 12, 1200-292 Lisboa', cat:'4' },
  { id:'h048', name:'Vincci Baixa', area:'Baixa', address:'Rua do Comércio 2, 1100-150 Lisboa', cat:'4' },
  { id:'h049', name:'Vincci Liberdade', area:'Liberdade', address:'Rua Rodrigo da Fonseca 2, 1250-191 Lisboa', cat:'4' },
  { id:'h050', name:'Eurostars das Letras', area:'Avenida da Liberdade', address:'Rua Conde de Redondo 41, 1150-102 Lisboa', cat:'4' },
  { id:'h051', name:'Eurostars Universal Lisboa', area:'Parque das Nações', address:'Avenida D. João II 47, 1990-085 Lisboa', cat:'4' },
  { id:'h052', name:'Eurostars Lisboa Parque', area:'Parque Eduardo VII', address:'Rua Castilho 72, 1250-071 Lisboa', cat:'4' },
  { id:'h053', name:'Turim Terreiro do Paço', area:'Baixa', address:'Rua do Comércio 9, 1100-148 Lisboa', cat:'4' },
  { id:'h054', name:'Turim Av. Liberdade', area:'Liberdade', address:'Avenida da Liberdade 20, 1250-144 Lisboa', cat:'4' },
  { id:'h055', name:'Turim Lisboa Hotel', area:'Saldanha', address:'Rua Tomás Ribeiro 42, 1050-225 Lisboa', cat:'4' },
  { id:'h056', name:'Turim Iberia Hotel', area:'Saldanha', address:'Avenida 5 de Outubro 160, 1050-026 Lisboa', cat:'4' },
  { id:'h057', name:'Turim Saldanha', area:'Saldanha', address:'Avenida da República 10, 1050-191 Lisboa', cat:'4' },
  { id:'h058', name:'Turim Europa', area:'Saldanha', address:'Avenida da República 15, 1050-185 Lisboa', cat:'3' },
  { id:'h059', name:'Turim Marquês', area:'Marquês de Pombal', address:'Rua Joaquim António de Aguiar 21, 1070-150 Lisboa', cat:'3' },
  { id:'h060', name:'Turim Restauradores', area:'Restauradores', address:'Praça dos Restauradores 68, 1250-188 Lisboa', cat:'3' },
  { id:'h061', name:'TURIM Boulevard Hotel', aka:'Turim Boulevard', area:'Avenida da Liberdade', address:'Avenida da Liberdade 15, 1250-096 Lisboa', cat:'4' },
  { id:'h062', name:'HF Fénix Lisboa', area:'Marquês de Pombal', address:'Praça Marquês de Pombal 8, 1269-133 Lisboa', cat:'4' },
  { id:'h063', name:'HF Fénix Garden', area:'Marquês de Pombal', address:'Rua Andrade Corvo 16, 1050-009 Lisboa', cat:'3' },
  { id:'h064', name:'HF Fénix Music', area:'Marquês de Pombal', address:'Rua Joaquim António de Aguiar 5, 1070-149 Lisboa', cat:'3' },
  { id:'h065', name:'HF Fénix Urban', area:'Saldanha', address:'Rua D. Estefânia 121, 1150-151 Lisboa', cat:'3' },
  { id:'h066', name:'Jupiter Lisboa Hotel', area:'Saldanha', address:'Avenida da República 46, 1050-195 Lisboa', cat:'4' },
  { id:'h067', name:'Hotel Florida', area:'Marquês de Pombal', address:'Rua Duque de Palmela 32, 1250-098 Lisboa', cat:'4' },
  { id:'h068', name:'Britania Hotel', aka:'Hotel Britania', area:'Avenida da Liberdade', address:'Rua Rodrigues Sampaio 17, 1150-278 Lisboa', cat:'4' },
  { id:'h069', name:'Hotel Mundial', area:'Rossio', address:'Praça Martim Moniz 2, 1100-341 Lisboa', cat:'4' },
  { id:'h070', name:'Hotel Portugal', area:'Baixa', address:'Rua João das Regras 4, 1100-294 Lisboa', cat:'3' },
  { id:'h071', name:'Portugal Boutique Hotel', area:'Baixa', address:'Rua João das Regras 4, 1100-294 Lisboa', cat:'4' },
  { id:'h072', name:'Lisboa Pessoa Hotel', area:'Chiado', address:'Rua da Oliveira ao Carmo 8, 1200-307 Lisboa', cat:'4' },
  { id:'h073', name:'Lisboa Carmo Hotel', area:'Chiado', address:'Rua da Oliveira ao Carmo 1, 1200-307 Lisboa', cat:'4' },
  { id:'h074', name:'My Story Hotel Rossio', area:'Rossio', address:'Praça D. Pedro IV 59, 1100-202 Lisboa', cat:'3' },
  { id:'h075', name:'My Story Hotel Tejo', aka:'My Story Tejo', area:'Baixa', address:'Rua dos Condes de Monsanto 2, 1100-159 Lisboa', cat:'3' },
  { id:'h076', name:'My Story Hotel Ouro', area:'Baixa', address:'Rua Áurea 100, 1100-063 Lisboa', cat:'3' },
  { id:'h077', name:'My Story Hotel Figueira', area:'Rossio', address:'Praça da Figueira 13, 1100-226 Lisboa', cat:'3' },
  { id:'h078', name:'Tryp Lisboa Aeroporto', area:'Aeroporto', address:'Aeroporto de Lisboa, Rua C, 1700-008 Lisboa', cat:'4' },
  { id:'h079', name:'ibis Lisboa Aeroporto', area:'Aeroporto', address:'Rua C, Aeroporto de Lisboa, 1749-078 Lisboa', cat:'3' },
  { id:'h080', name:'Star Inn Lisbon Airport', area:'Aeroporto', address:'Rua C do Aeroporto, 1700-008 Lisboa', cat:'3' },
  { id:'h081', name:'ibis Lisboa Centro Saldanha', area:'Saldanha', address:'Avenida Casal Ribeiro 23, 1000-090 Lisboa', cat:'3' },
  { id:'h082', name:'ibis Styles Lisboa Centro Marquês de Pombal', area:'Marquês de Pombal', address:'Rua Braamcamp 10, 1250-050 Lisboa', cat:'3' },
  { id:'h083', name:'ibis Styles Lisboa Centro Liberdade', area:'Liberdade', address:'Rua Rodrigo da Fonseca 82, 1250-193 Lisboa', cat:'3' },
  { id:'h084', name:'ibis Lisboa Parque das Nações', area:'Parque das Nações', address:'Avenida D. João II, Lote 1.02, 1990-077 Lisboa', cat:'3' },
  { id:'h085', name:'Holiday Inn Lisbon Continental', area:'Entrecampos', address:'Rua Laura Alves 9, 1069-169 Lisboa', cat:'4' },
  { id:'h086', name:'Holiday Inn Express Lisboa Av. Liberdade', area:'Liberdade', address:'Rua Alexandre Herculano 40, 1250-011 Lisboa', cat:'3' },
  { id:'h087', name:'Novotel Lisboa', area:'Sete Rios', address:'Avenida José Malhoa 1, 1099-051 Lisboa', cat:'4' },
  { id:'h088', name:'Mercure Lisboa', area:'Saldanha', address:'Avenida da Liberdade 20, 1250-144 Lisboa', cat:'4' },
  { id:'h089', name:'The Ivens Autograph Collection', area:'Chiado', address:'Rua Capelo 5, 1200-242 Lisboa', cat:'5' },
  { id:'h090', name:'Andaz Lisbon by Hyatt', area:'Baixa', address:'Rua do Comércio 132, 1100-150 Lisboa', cat:'5' },
  { id:'h091', name:'Hyatt Regency Lisbon', area:'Parque das Nações', address:'Avenida D. João II, 1990-083 Lisboa', cat:'5' },
  { id:'h092', name:'ME by Meliá Lisbon', area:'Chiado', address:'Largo do Chiado 16, 1200-108 Lisboa', cat:'5' },
  { id:'h093', name:'Meliá Lisboa Oriente', area:'Parque das Nações', address:'Avenida D. João II, Lote 1.16, 1990-083 Lisboa', cat:'4' },
  { id:'h094', name:'Iberostar Selection Lisboa', area:'Rato', address:'Rua Alexandre Herculano 13, 1150-005 Lisboa', cat:'5' },
  { id:'h095', name:'PortoBay Liberdade', aka:'PortoBay Liberdade hostel-hôtel', area:'Avenida da Liberdade', address:'Rua Rosa Araújo 8, 1250-194 Lisboa', cat:'5' },
  { id:'h096', name:'The Vintage Lisboa Hotel', aka:'The Vintage Hotel & Spa Lisbon', area:'Rato', address:'Rua Rodrigo da Fonseca 2, 1250-190 Lisboa', cat:'5' },
  { id:'h097', name:'Pousada de Lisboa', area:'Praça do Comércio', address:'Praça do Comércio 31, 1100-148 Lisboa', cat:'5' },
  { id:'h098', name:'Corpo Santo Lisbon Historical Hotel', area:'Cais do Sodré', address:'Largo do Corpo Santo 25, 1200-129 Lisboa', cat:'5' },
  { id:'h099', name:'Verride Palácio Santa Catarina', area:'Santa Catarina', address:'Rua de Santa Catarina 1, 1200-401 Lisboa', cat:'5' },
  { id:'h100', name:'Palácio do Governador', area:'Belém', address:'Rua Bartolomeu Dias 117, 1400-026 Lisboa', cat:'5' },
  { id:'h101', name:'Torel Palace Lisbon', area:'São Pedro de Alcântara', address:'Rua Tóquio 6, 1200-221 Lisboa', cat:'5' },
  { id:'h102', name:'Sublime Lisboa Príncipe Real', aka:'Sublime Lisboa São Bento', area:'Príncipe Real', address:'Rua de São Bento 39, 1200-109 Lisboa', cat:'5' },
  { id:'h103', name:'Hotel das Amoreiras', area:'Amoreiras', address:'Praça das Amoreiras 34, 1250-020 Lisboa', cat:'4' },
  { id:'h104', name:'Heritage Av Liberdade Hotel', aka:'Heritage Avenida Liberdade', area:'Avenida da Liberdade', address:'Avenida da Liberdade 28, 1250-145 Lisboa', cat:'4' },
  { id:'h105', name:'Hotel Lisboa Plaza', area:'Avenida da Liberdade', address:'Travessa do Salitre 7, 1269-066 Lisboa', cat:'4' },
  { id:'h106', name:'As Janelas Verdes', area:'Lapa', address:'Rua das Janelas Verdes 47, 1200-690 Lisboa', cat:'4' },
  { id:'h107', name:'York House Lisboa', area:'Lapa', address:'Rua das Janelas Verdes 32, 1200-691 Lisboa', cat:'4' },
  { id:'h108', name:'Palácio Ramalhete', area:'Santos', address:'Rua das Janelas Verdes 92, 1200-693 Lisboa', cat:'4' },
  { id:'h109', name:'AlmaLusa Baixa/Chiado', area:'Baixa', address:'Praça do Município 21, 1100-365 Lisboa', cat:'4' },
  { id:'h110', name:'Hotel do Chiado', area:'Chiado', address:'Rua Nova do Almada 114, 1200-290 Lisboa', cat:'4' },
  { id:'h111', name:'1908 Lisboa Hotel', aka:'Casa do Intendente', area:'Intendente', address:'Largo do Intendente Pina Manique 6, 1100-285 Lisboa', cat:'4' },
  { id:'h112', name:'Convent Square Lisbon', area:'Baixa', address:'Rua Dom Antão de Almada 4, 1100-018 Lisboa', cat:'5' },
  { id:'h113', name:'Locke de Santa Joana', area:'Avenida da Liberdade', address:'Rua Camilo Castelo Branco 18, 1150-084 Lisboa', cat:'4' },
  { id:'h114', name:'Internacional Design Hotel', area:'Rossio', address:'Rua da Betesga 3, 1100-090 Lisboa', cat:'4' },
  { id:'h115', name:'Lumen Hotel', area:'Avenida da Liberdade', address:'Rua do Telhal 4, 1150-344 Lisboa', cat:'4' },
  { id:'h116', name:'Hotel Marquês de Pombal', area:'Marquês de Pombal', address:'Avenida da Liberdade 243, 1250-143 Lisboa', cat:'4' },
  { id:'h117', name:'BessaHotel Liberdade', area:'Liberdade', address:'Avenida da Liberdade 111, 1250-140 Lisboa', cat:'4' },
  { id:'h118', name:'Avani Avenida Liberdade Lisbon', area:'Avenida da Liberdade', address:'Avenida da Liberdade 240, 1250-148 Lisboa', cat:'4' },
  { id:'h119', name:'The Emerald House Lisbon', area:'Estrela', address:'Rua de São Marçal 77, 1200-421 Lisboa', cat:'4' },
  { id:'h120', name:'Hotel Príncipe Real', area:'Príncipe Real', address:'Rua da Escola Politécnica 149, 1250-101 Lisboa', cat:'4' },
  { id:'h121', name:'Neya Lisboa Hotel', area:'Campo de Santana', address:'Rua de D. Estefânia 71, 1000-154 Lisboa', cat:'4' },
  { id:'h122', name:'Czar Lisbon Hotel', area:'Avenida da Liberdade', address:'Rua Braamcamp 81, 1250-051 Lisboa', cat:'4' },
  { id:'h123', name:'Lutecia Smart Design Hotel', area:'Roma', address:'Avenida Frei Miguel Contreiras 52, 1700-213 Lisboa', cat:'4' },
  { id:'h124', name:'Hotel Açores Lisboa', area:'Entrecampos', address:'Avenida Columbano Bordalo Pinheiro 3, 1070-060 Lisboa', cat:'4' },
  { id:'h125', name:'VIP Executive Entrecampos', area:'Entrecampos', address:'Avenida 5 de Outubro 160, 1050-026 Lisboa', cat:'4' },
  { id:'h126', name:'VIP Executive Saldanha', area:'Saldanha', address:'Avenida Fontes Pereira de Melo 42, 1050-119 Lisboa', cat:'4' },
  { id:'h127', name:'VIP Executive Zurique', area:'Saldanha', address:'Rua Ivone Silva 18, 1050-124 Lisboa', cat:'3' },
  { id:'h128', name:'VIP Inn Berna', area:'Saldanha', address:'Avenida da República 8, 1050-191 Lisboa', cat:'3' },
  { id:'h129', name:'VIP Grand Lisboa Hotel & Spa', area:'Saldanha', address:'Avenida 5 de Outubro 197, 1050-053 Lisboa', cat:'5' },
  { id:'h130', name:'VIP Executive Eden', area:'Restauradores', address:'Praça dos Restauradores 24, 1250-187 Lisboa', cat:'4' },
  { id:'h131', name:'Vila Galé Ópera', area:'Alcântara', address:'Travessa do Conde da Ponte, 1300-141 Lisboa', cat:'4' },
  { id:'h132', name:'Real Palácio Hotel', aka:'Hotel Real Palácio', area:'Saldanha', address:'Rua Tomás Ribeiro 115, 1050-228 Lisboa', cat:'5' },
  { id:'h133', name:'Hotel 3K Madrid', area:'Avenida de Madrid', address:'Rua de Moscavide, 1800 Lisboa', cat:'4' },
  { id:'h134', name:'Mama Shelter Lisboa', area:'Intendente', address:'Rua da Palmeira 36, 1200-311 Lisboa', cat:'3' },
  { id:'h135', name:'Moxy Lisbon City', area:'Parque das Nações', address:'Rua Cais das Naus, 1990-173 Lisboa', cat:'3' },
  { id:'h136', name:'Moxy Lisboa Oriente', area:'Oriente', address:'Avenida D. João II, 1990-083 Lisboa', cat:'3' },
  { id:'h137', name:'Hotel Roma', area:'Areeiro', address:'Avenida de Roma 24, 1000-268 Lisboa', cat:'3' },
  { id:'h138', name:'Rossio Plaza Hotel', area:'Rossio', address:'Rua Áurea 266, 1100-063 Lisboa', cat:'3' },
  { id:'h139', name:'Hotel Borges Chiado', area:'Chiado', address:'Rua Garrett 108, 1200-205 Lisboa', cat:'3' },
  { id:'h140', name:'Hotel Avenida Park', area:'Parque Eduardo VII', address:'Avenida Sidónio Pais 6, 1050-214 Lisboa', cat:'3' },
  { id:'h141', name:'Hotel Miraparque', area:'Parque Eduardo VII', address:'Avenida Sidónio Pais 12, 1050-214 Lisboa', cat:'3' },
  { id:'h142', name:'Hotel Alif Campo Pequeno', area:'Campo Pequeno', address:'Avenida da República 11, 1050-185 Lisboa', cat:'3' },
  { id:'h143', name:'Hotel Nacional', area:'Restauradores', address:'Rua João das Regras 4, 1100-294 Lisboa', cat:'3' },
  { id:'h144', name:'Hotel Santa Justa', area:'Baixa', address:'Rua de Santa Justa 38, 1100-485 Lisboa', cat:'3' },
  { id:'h145', name:'Hotel da Baixa', area:'Baixa', address:'Rua da Prata 231, 1100-416 Lisboa', cat:'3' },
  { id:'h146', name:'Hotel Lis Baixa', area:'Baixa', address:'Rua dos Douradores 196, 1100-207 Lisboa', cat:'3' },
  { id:'h147', name:'Hotel Inn Rossio', area:'Rossio', address:'Rua dos Sapateiros 167, 1100-579 Lisboa', cat:'3' },
  { id:'h148', name:'Stay Hotel Lisboa Centro Chiado', area:'Chiado', address:'Rua do Crucifixo 84, 1100-183 Lisboa', cat:'3' },
  { id:'h149', name:'easyHotel Lisbon', area:'Avenida da Liberdade', address:'Rua de Santa Marta 60A, 1150-297 Lisboa', cat:'2' },
  { id:'h150', name:'Hotel Jorge V', area:'Marquês de Pombal', address:'Rua Rodrigo da Fonseca 64, 1250-193 Lisboa', cat:'3' },
  { id:'h151', name:'Hotel Excelsior', area:'Restauradores', address:'Rua Rodrigues Sampaio 172, 1150-262 Lisboa', cat:'2' },
  { id:'h152', name:'Residencial Horizonte', area:'Saldanha', address:'Avenida António Augusto de Aguiar 42, 1050-017 Lisboa', cat:'2' },
  { id:'h153', name:'Residencial João XXI', area:'Avenida de Roma', address:'Rua Gomes Freire 155, 1150-177 Lisboa', cat:'2' },
  { id:'h154', name:'Residencial do Areeiro', area:'Areeiro', address:'Praça Francisco Sá Carneiro 4, 1000-160 Lisboa', cat:'2' },
  { id:'h155', name:'Pensão Praça da Figueira', area:'Rossio', address:'Travessa Nova de São Domingos 10, 1100-372 Lisboa', cat:'gh' },
  { id:'h156', name:'Lisbon Story Guesthouse Rossio', area:'Rossio', address:'Largo de São Domingos 2, 1100-201 Lisboa', cat:'gh' },
  { id:'h157', name:'Casa Balthazar', area:'Chiado', address:'Rua do Duque 26, 1200-158 Lisboa', cat:'gh' },
  { id:'h158', name:'Casa do Barão', area:'Alfama', address:'Rua do Barão 10, 1100-070 Lisboa', cat:'gh' },
  { id:'h159', name:'Casa Oliver Boutique B&B', area:'Príncipe Real', address:'Rua da Palmeira 33, 1200-311 Lisboa', cat:'gh' },
  { id:'h160', name:'The Original Lisbon Guesthouse', area:'Graça', address:'Rua da Senhora do Monte 40, 1170-346 Lisboa', cat:'gh' },
  { id:'h161', name:'Lisbon Wine House', area:'Bairro Alto', address:'Rua da Rosa 2, 1200-382 Lisboa', cat:'gh' },
  { id:'h162', name:'Palácio das Especiarias', area:'Mouraria', address:'Rua das Farinhas 1, 1100-140 Lisboa', cat:'gh' },
  { id:'h163', name:'Palacete Chafariz d\'El Rei', area:'Alfama', address:'Travessa do Chafariz de Dentro 6, 1100-139 Lisboa', cat:'4' },
  { id:'h164', name:'Convento do Salvador', aka:'Hotel Convento do Salvador', area:'Alfama', address:'Rua do Salvador 24, 1100-461 Lisboa', cat:'3' },
  { id:'h165', name:'Pousada Alfama', area:'Alfama', address:'Rua das Escolas Gerais 3, 1100-218 Lisboa', cat:'3' },
  { id:'h166', name:'Home Lisbon Hostel', area:'Baixa', address:'Rua de São Nicolau 13, 1100-548 Lisboa', cat:'hostel' },
  { id:'h167', name:'Living Lounge Hostel', area:'Baixa', address:'Rua do Crucifixo 116, 1100-183 Lisboa', cat:'hostel' },
  { id:'h168', name:'Yes! Lisbon Hostel Baixa', area:'Baixa', address:'Rua de São Julião 148, 1100-527 Lisboa', cat:'hostel' },
  { id:'h169', name:'Lost Inn Lisbon Bairro Alto', area:'Bairro Alto', address:'Rua Dom Pedro V 56, 1250-092 Lisboa', cat:'hostel' },
  { id:'h170', name:'Lisbon Destination Hostel', area:'Rossio', address:'Largo do Duque do Cadaval 17, 1200-160 Lisboa', cat:'hostel' },
  { id:'h171', name:'This is Lisbon Hostel', area:'Mouraria', address:'Rua da Costa do Castelo 63, 1100-179 Lisboa', cat:'hostel' },
  { id:'h172', name:'Oasis Backpackers\' Mansion', area:'Cais do Sodré', address:'Rua de Santa Catarina 24, 1200-401 Lisboa', cat:'hostel' },
  { id:'h173', name:'Martinhal Lisbon Chiado', area:'Chiado', address:'Rua Garrett 30, 1200-204 Lisboa', cat:'apart' },
  { id:'h174', name:'Upon Lisbon Prime Residences', area:'Avenida da Liberdade', address:'Rua Rodrigo da Fonseca 82, 1250-193 Lisboa', cat:'apart' },
  { id:'h175', name:'VIP Executive Suites do Marquês', area:'Marquês de Pombal', address:'Avenida Duque de Loulé 45, 1050-089 Lisboa', cat:'apart' },
  { id:'h176', name:'Legendary Lisboa Suites', area:'Baixa', address:'Rua da Prata 110, 1100-415 Lisboa', cat:'apart' },
  { id:'h177', name:'Figueira by The Beautique Hotels', area:'Rossio', address:'Praça da Figueira 11, 1100-226 Lisboa', cat:'4' },
  { id:'h178', name:'9Hotel Mercy', area:'Chiado', address:'Rua de Misericórdia 76, 1200-273 Lisboa', cat:'4' },
  { id:'h179', name:'Wine & Books Lisboa Hotel', area:'Ajuda', address:'Travessa da Memória 56, 1300-401 Lisboa', cat:'5' },
  { id:'h180', name:'Montebelo Vista Alegre Lisboa Chiado', area:'Chiado', address:'Largo do Chiado 23, 1200-108 Lisboa', cat:'5' },
  { id:'h181', name:'The Editory Riverside', area:'Cais do Sodré', address:'Rua do Instituto Industrial 6, 1200-225 Lisboa', cat:'5' },
  { id:'h182', name:'Art Legacy Hotel Baixa-Chiado', area:'Baixa', address:'Rua da Vitória 88, 1100-618 Lisboa', cat:'4' },
  { id:'h183', name:'Browns Central Hotel', area:'Baixa', address:'Rua da Vitória 133, 1100-619 Lisboa', cat:'4' },
  { id:'h184', name:'Browns Boutique Hotel', area:'Baixa', address:'Rua da Vitória 88, 1100-618 Lisboa', cat:'3' },
  { id:'h185', name:'Hotel X Avenida Liberdade', area:'Avenida da Liberdade', address:'Travessa da Glória 22, 1250-118 Lisboa', cat:'4' },
  { id:'h186', name:'138 Liberdade Hotel', area:'Avenida da Liberdade', address:'Avenida da Liberdade 138, 1250-146 Lisboa', cat:'4' },
  { id:'h187', name:'Zenit Lisboa', area:'Saldanha', address:'Avenida 5 de Outubro 11, 1050-047 Lisboa', cat:'4' },
  { id:'h188', name:'Hotel Príncipe Lisboa', area:'Avenida da Liberdade', address:'Avenida Duque de Ávila 201, 1050-082 Lisboa', cat:'3' },
  { id:'h189', name:'Hotel A.S. Lisboa', area:'Saldanha', address:'Avenida Almirante Reis 188, 1000-055 Lisboa', cat:'3' },
  { id:'h190', name:'Lisbon City Hotel', area:'Avenida Almirante Reis', address:'Avenida Almirante Reis 115, 1150-014 Lisboa', cat:'3' },
  { id:'h191', name:'Empire Lisbon Hotel', area:'Saldanha', address:'Rua de D. Estefânia 49, 1000-153 Lisboa', cat:'3' },
  { id:'h192', name:'Hotel Travel Park Lisboa', area:'Saldanha', address:'Avenida Almirante Reis 64, 1150-020 Lisboa', cat:'3' },
  { id:'h193', name:'The Lift Boutique Hotel', area:'Baixa', address:'Rua de Santa Justa 7, 1100-485 Lisboa', cat:'3' },
  { id:'h194', name:'Rossio Garden Hotel', area:'Rossio', address:'Calçada do Carmo 25, 1200-091 Lisboa', cat:'3' },
  { id:'h195', name:'Hotel Lisboa', area:'Avenida da Liberdade', address:'Rua Barata Salgueiro 5, 1250-042 Lisboa', cat:'4' },
  { id:'h196', name:'Evolution Lisboa Hotel', area:'Parque das Nações', address:'Avenida D. João II, 1990-083 Lisboa', cat:'4' },
  { id:'h197', name:'Lux Lisboa Park', area:'Parque Eduardo VII', address:'Rua Braamcamp 10A, 1250-050 Lisboa', cat:'4' },
  { id:'h198', name:'Ramada by Wyndham Lisbon', area:'Sete Rios', address:'Avenida Engenheiro Duarte Pacheco 205, 1070-103 Lisboa', cat:'4' },
  { id:'h199', name:'Hotel Alif Campo Pequeno Suites', area:'Campo Pequeno', address:'Avenida de Berna 64, 1050-043 Lisboa', cat:'3' },
  { id:'h200', name:'Masa Hotel 5 de Outubro', area:'Saldanha', address:'Avenida 5 de Outubro 53, 1050-049 Lisboa', cat:'3' },
  { id:'h201', name:'Masa Hotel & Spa Campo Grande', area:'Campo Grande', address:'Campo Grande 7B, 1700-087 Lisboa', cat:'4' },
  { id:'h202', name:'The Hotel Masa Almirante', area:'Arroios', address:'Avenida Almirante Reis 68, 1150-020 Lisboa', cat:'3' },
  { id:'h203', name:'Ikonik Lisboa', area:'Parque das Nações', address:'Avenida D. João II, 1990-085 Lisboa', cat:'3' },
  { id:'h204', name:'Dorma Saldanha', area:'Saldanha', address:'Avenida da República 47, 1050-195 Lisboa', cat:'3' },
  { id:'h205', name:'Dorma Liberdade', area:'Liberdade', address:'Rua Alexandre Herculano 16, 1250-012 Lisboa', cat:'3' },
  { id:'h206', name:'Jam Lisbon Hotel', area:'Intendente', address:'Rua dos Anjos 6, 1150-034 Lisboa', cat:'3' },
  { id:'h207', name:'Tempo FLH Hotels Lisboa', area:'Baixa', address:'Rua dos Sapateiros 84, 1100-578 Lisboa', cat:'3' },
  { id:'h208', name:'Ferraria XVI FLH Hotels', area:'Baixa', address:'Rua dos Sapateiros 84, 1100-578 Lisboa', cat:'3' },
  { id:'h209', name:'Aurea Museum by Eurostars', area:'Cais do Sodré', address:'Rua Cais do Sodré 1, 1200-108 Lisboa', cat:'4' },
  { id:'h210', name:'Eurostars Museum', area:'Cais do Sodré', address:'Rua do Cais do Sodré 2, 1200-108 Lisboa', cat:'4' },
  { id:'h211', name:'SMY Lisboa Hotel', area:'Saldanha', address:'Avenida Fontes Pereira de Melo 35, 1050-118 Lisboa', cat:'3' },
  { id:'h212', name:'Le Consulat Hotel', area:'Príncipe Real', address:'Praça do Príncipe Real 26, 1250-184 Lisboa', cat:'4' },
  { id:'h213', name:'Dos Reis by The Beautique Hotels', area:'Chiado', address:'Rua Garrett 47, 1200-203 Lisboa', cat:'4' },
  { id:'h214', name:'Palácio do Visconde Chiado', area:'Chiado', address:'Rua da Misericórdia 95, 1200-272 Lisboa', cat:'4' },
  { id:'h215', name:'Feeling Chiado 15', area:'Chiado', address:'Rua da Misericórdia 15, 1200-273 Lisboa', cat:'gh' },
  { id:'h216', name:'Lisbon Wine Hotel', area:'Bairro Alto', address:'Rua da Rosa 111, 1200-385 Lisboa', cat:'gh' },
  { id:'h217', name:'Hotel Miradouro de Santa Luzia', area:'Alfama', address:'Largo de Santa Luzia, 1100-487 Lisboa', cat:'gh' },
  { id:'h218', name:'262 Boutique Hotel', area:'Baixa', address:'Rua da Prata 262, 1100-424 Lisboa', cat:'3' },
  { id:'h219', name:'PH Downtown Suites', area:'Baixa', address:'Rua da Madalena 201, 1100-319 Lisboa', cat:'apart' },
  { id:'h220', name:'Lisbon Arsenal Suites', area:'Campo de Santa Clara', address:'Rua do Arsenal 130, 1100-038 Lisboa', cat:'apart' },
  { id:'h221', name:'Olivia Lisboa Hotel', area:'Saldanha', address:'Avenida Fontes Pereira de Melo 35, 1050-118 Lisboa', cat:'3' },
  { id:'h222', name:'Hotel Dublin', area:'Saldanha', address:'Rua de D. Estefânia 45, 1000-153 Lisboa', cat:'2' },
  { id:'h223', name:'Next Hotel Lisboa', area:'Saldanha', address:'Avenida Duque de Ávila 201, 1050-082 Lisboa', cat:'3' },
  { id:'h224', name:'America Diamonds Hotel', area:'Saldanha', address:'Rua Tomás Ribeiro 47, 1050-226 Lisboa', cat:'3' },
  { id:'h225', name:'Lisboa Central Park Hotel', area:'Parque Eduardo VII', address:'Avenida Sidónio Pais 4, 1050-214 Lisboa', cat:'apart' },

  /* Liste étendue — boutique, hostels, apart-hôtels, Graça/Mouraria, Belém, Parque das Nações */
  { id:'h226', name:'The Independente Suites & Terrace', area:'Bairro Alto', address:'Rua de São Pedro de Alcântara 81, 1250-238 Lisboa', cat:'4' },
  { id:'h227', name:'Independente Hostel & Suites', aka:'The Independente Hostel & Suites', area:'Bairro Alto', address:'Rua de São Pedro de Alcântara 81, 1250-238 Lisboa', cat:'hostel' },
  { id:'h228', name:'The Independente Collective (Anti)', aka:'The Independente Collective Anti', area:'Intendente', address:'Largo do Intendente 21, 1100-283 Lisboa', cat:'gh' },
  { id:'h229', name:'Palácio Príncipe Real', area:'Príncipe Real', address:'Rua da Alegria 12, 1250-004 Lisboa', cat:'5' },
  { id:'h230', name:'Casa do Príncipe', area:'Príncipe Real', address:'Praça do Príncipe Real 23, 1250-184 Lisboa', cat:'gh' },
  { id:'h231', name:'Torel Palace Lisboa', area:'Torel', address:'Rua Câmara Pestana 23, 1150-084 Lisboa', cat:'5' },
  { id:'h232', name:'Casa Amora Guesthouse', area:'Amoreiras', address:'Travessa das Amoreiras 11, 1250-025 Lisboa', cat:'gh' },
  { id:'h233', name:'Casa das Janelas com Vista', area:'Alfama', address:'Rua da Regueira 3-9, 1100-596 Lisboa', cat:'gh' },
  { id:'h234', name:'Dear Lisbon Boutique Hotel', aka:'Dear Lisbon Charming House', area:'Chiado', address:'Rua do Alecrim 12, 1200-014 Lisboa', cat:'4' },
  { id:'h235', name:'Sublime Lisboa', aka:'Sublime Lisboa Alcântara', area:'Alcântara', address:'Rua Rodrigues Faria 103, 1300-501 Lisboa', cat:'5' },
  { id:'h236', name:'Palácio Belmonte', area:'Castelo', address:'Páteo Dom Fradique 14, 1100-624 Lisboa', cat:'5' },
  { id:'h237', name:'H10 Duque de Loulé', area:'Marquês de Pombal', address:'Rua Duque de Loulé 109, 1050-089 Lisboa', cat:'4' },
  { id:'h238', name:'Brown\'s Downtown Hotel', area:'Baixa', address:'Rua da Madalena 211, 1100-333 Lisboa', cat:'4' },
  { id:'h239', name:'Hotel Amazónia Lisboa', area:'Amoreiras', address:'Travessa da Fábrica dos Pentes 12, 1250-106 Lisboa', cat:'3' },
  { id:'h240', name:'Hotel Dom Carlos Park', area:'Marquês de Pombal', address:'Avenida Duque de Loulé 121, 1050-089 Lisboa', cat:'3' },
  { id:'h242', name:'Lisboa Santos Hotel', area:'Santos', address:'Largo Vitorino Damásio 4, 1200-867 Lisboa', cat:'3' },
  { id:'h243', name:'Hotel Zenit Lisboa', area:'Saldanha', address:'Avenida 5 de Outubro 11, 1050-047 Lisboa', cat:'4' },

  { id:'h244', name:'Sunset Destination Hostel', area:'Cais do Sodré', address:'Estação de Cais do Sodré, 1200-159 Lisboa', cat:'hostel' },
  { id:'h245', name:'Goodmorning Hostel', area:'Rossio', address:'Rua da Betesga 3, 3º, 1100-090 Lisboa', cat:'hostel' },
  { id:'h246', name:'Travellers House', area:'Baixa', address:'Rua Augusta 89, 1100-053 Lisboa', cat:'hostel' },
  { id:'h247', name:'Hub New Lisbon Hostel', area:'Baixa', address:'Rua da Assunção 82, 1100-044 Lisboa', cat:'hostel' },
  { id:'h248', name:'Pousada da Juventude de Lisboa (Movijovem)', aka:'Pousada da Juventude de Lisboa', area:'Saldanha', address:'Rua Andrade Corvo 46, 1050-009 Lisboa', cat:'hostel' },
  { id:'h249', name:'Yellow Hostel Lisbon', area:'Chiado', address:'Rua da Trindade 24, 1200-467 Lisboa', cat:'hostel' },
  { id:'h250', name:'Rossio Hostel & Suites', area:'Rossio', address:'Rua da Betesga 3, 1100-090 Lisboa', cat:'hostel' },
  { id:'h251', name:'Nice Way Chiado Hostel', area:'Chiado', address:'Rua Nova do Almada 12, 1200-288 Lisboa', cat:'hostel' },
  { id:'h252', name:'Yes! Lisbon Hostel', aka:'Yes! Lisbon Hostel Rato', area:'Rato', address:'Rua Rodrigo da Fonseca 3, 1250-189 Lisboa', cat:'hostel' },
  { id:'h253', name:'Lost Inn Lisbon', aka:'Lost Inn Lisbon Martim Moniz', area:'Martim Moniz', address:'Rua do Benformoso 175, 1100-085 Lisboa', cat:'hostel' },
  { id:'h254', name:'Lisbon Story Guesthouse', aka:'Lisbon Story Guesthouse Martim Moniz', area:'Martim Moniz', address:'Rua do Benformoso 182, 1100-085 Lisboa', cat:'gh' },
  { id:'h255', name:'Lisbon Calling Hostel', area:'Santos', address:'Rua de São Paulo 126, 1200-429 Lisboa', cat:'hostel' },
  { id:'h256', name:'Inn Possible Lisbon Hostel', area:'Anjos', address:'Rua da Palma 70, 1100-394 Lisboa', cat:'hostel' },
  { id:'h257', name:'Goodnight Hostel', area:'Baixa', address:'Rua dos Correeiros 113, 1100-163 Lisboa', cat:'hostel' },
  { id:'h258', name:'Lisbon Lounge Hostel', area:'Baixa', address:'Rua de São Nicolau 41, 1100-547 Lisboa', cat:'hostel' },

  { id:'h259', name:'TM Luxury Apartments Lisbon', area:'Baixa', address:'Rua Áurea 253, 1100-066 Lisboa', cat:'apart' },
  { id:'h260', name:'Feels Like Home Baixa Chic Apartments', area:'Baixa', address:'Rua da Prata 260, 1100-421 Lisboa', cat:'apart' },
  { id:'h261', name:'Feels Like Home Prata Marina Apartments', area:'Baixa', address:'Rua da Prata 108, 1100-417 Lisboa', cat:'apart' },
  { id:'h262', name:'Lisbon Serviced Apartments', area:'Baixa', address:'Rua dos Fanqueiros 116, 1100-231 Lisboa', cat:'apart' },
  { id:'h263', name:'Chiado 16 Apartments', area:'Chiado', address:'Rua Nova do Almada 16, 1200-288 Lisboa', cat:'apart' },
  { id:'h264', name:'Lisbon Five Stars Apartments', aka:'Lisbon Five Stars Apartments Chiado', area:'Chiado', address:'Rua Nova da Trindade 5, 1200-303 Lisboa', cat:'apart' },
  { id:'h265', name:'Palácio do Visconde – The Coffee Experience', aka:'Palácio do Visconde The Coffee Experience', area:'Santos', address:'Praça de São Paulo 8, 1200-425 Lisboa', cat:'apart' },
  { id:'h266', name:'BO29 Apartments', area:'Bica', address:'Rua do Boavista 29, 1200-069 Lisboa', cat:'apart' },
  { id:'h267', name:'Riverside Lisbon Apartments', area:'Beato', address:'Avenida Infante Dom Henrique, Armazém B, 1900-264 Lisboa', cat:'apart' },
  { id:'h268', name:'The Lisboans Apartments', area:'Baixa', address:'Rua da Madalena 84, 1100-337 Lisboa', cat:'apart' },

  { id:'h269', name:'Jerónimos 8 Hotel', area:'Belém', address:'Rua dos Jerónimos 8, 1400-211 Lisboa', cat:'4' },
  { id:'h270', name:'Hilton Lisbon Park Hotel', aka:'Hilton Lisbon Park', area:'Parque das Nações', address:'Cais das Naus, Lote 2.09.01, 1990-169 Lisboa', cat:'4' },
  { id:'h271', name:'Tryp Lisboa Oriente', area:'Parque das Nações', address:'Avenida D. João II, Lote 1.19.02, 1990-083 Lisboa', cat:'4' },

  { id:'h272', name:'Casa da Baronesa', area:'Graça', address:'Rua da Voz do Operário 60, 1170-353 Lisboa', cat:'gh' },
  { id:'h273', name:'2861 Lisboa Hotel', area:'Mouraria', address:'Rua João do Outeiro 3, 1100-291 Lisboa', cat:'3' },
  { id:'h274', name:'Palacio Camaguey Guesthouse', area:'Mouraria', address:'Rua João do Outeiro 8, 1100-291 Lisboa', cat:'gh' },
  { id:'h275', name:'The House of Wonders', area:'Graça', address:'Beco do Meio à Graça 5, 1170-115 Lisboa', cat:'gh' },
  { id:'h276', name:'Casa de São Mamede', area:'Príncipe Real', address:'Rua da Escola Politécnica 159, 1250-101 Lisboa', cat:'gh' },

  { id:'h277', name:'Palácio Estoril Hotel Golf & Spa', area:'Estoril', address:'Rua Particular, 2769-504 Estoril', cat:'5' },
  { id:'h278', name:'InterContinental Cascais-Estoril', area:'Estoril', address:'Avenida Marginal 8023, 2769-905 Estoril', cat:'5' },
  { id:'h279', name:'Grande Real Villa Itália Hotel & Spa', area:'Cascais', address:'Rua Frei Nicolau de Oliveira 100, 2750-641 Cascais', cat:'5' },
  { id:'h280', name:'Hotel Albatroz', area:'Cascais', address:'Rua Frederico Arouca 100, 2750-353 Cascais', cat:'5' },
  { id:'h281', name:'Cascais Miragem Hotel', area:'Cascais', address:'Avenida Marginal 8554, 2754-536 Cascais', cat:'5' },
  { id:'h282', name:'The Oitavos', area:'Cascais', address:'Rua de Oitavos, Quinta da Marinha, 2750-374 Cascais', cat:'5' },
  { id:'h283', name:'Fortaleza do Guincho', area:'Guincho', address:'Estrada do Guincho, 2750-642 Cascais', cat:'5' },
  { id:'h284', name:'Vila Galé Collection Palácio dos Arcos', address:'Rua Costa Pinto 17, 2770-045 Paço de Arcos', area:'Paço de Arcos', cat:'5' },
  { id:'h285', name:'Pestana Cascais Ocean & Conference Hotel', area:'Cascais', address:'Avenida Rei Humberto II de Itália, 2754-509 Cascais', cat:'4' },
  { id:'h286', name:'Hotel Inglaterra Estoril', area:'Estoril', address:'Rua do Porto 1, 2765-271 Estoril', cat:'4' },
  { id:'h287', name:'Tivoli Palácio de Seteais', area:'Sintra', address:'Rua Barbosa du Bocage 8, 2710-517 Sintra', cat:'5' },
  { id:'h288', name:'Tivoli Sintra', area:'Sintra', address:'Praça da República 3, 2710-616 Sintra', cat:'4' },
  { id:'h289', name:'Penha Longa Resort', area:'Sintra', address:'Estrada da Lagoa Azul, Linhó, 2714-511 Sintra', cat:'5' },
  { id:'h290', name:'Lawrence\'s Hotel Sintra', area:'Sintra', address:'Rua Consiglieri Pedroso 38, 2710-550 Sintra', cat:'4' },
  { id:'h291', name:'Casa do Intendente', area:'Intendente', address:'Largo do Intendente Pina Manique 6, 1100-285 Lisboa', cat:'gh' },
  { id:'h292', name:'Guest House Arroios', area:'Arroios', address:'Zona de Arroios, 1170 Lisboa', cat:'gh' },
  { id:'h293', name:'Casa Amora Campo de Ourique', area:'Campo de Ourique', address:'Rua Ferreira Borges, 1350 Lisboa', cat:'gh' },
  { id:'h294', name:'Herdade da Fonte Santa', area:'Periferia de Lisboa', address:'Periferia de Lisboa — morada a confirmar no check-in', cat:'gh' }
];
